source: https://github.com/MEDSL/2024-elections-official/blob/main/individual_states/de24.zip

In [99]:
import geopandas
import numpy as np
import pandas as pd

In [100]:
df = pd.read_csv("../data/Delaware/de24_cleaned.csv")

In [101]:
print(f"shape: {df.shape}")
df.head()

shape: (48504, 24)

,precinct,office,party_detailed,party_simplified,mode,votes,county_name,county_fips,jurisdiction_name,jurisdiction_fips,...,stage,state,special,writein,state_po,state_fips,state_cen,state_ic,date,magnitude
0,39-01,STATE HOUSE,REPUBLICAN,REPUBLICAN,IN-PERSON,257,SUSSEX,10005,SUSSEX,10005,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
1,39-02,STATE HOUSE,REPUBLICAN,REPUBLICAN,IN-PERSON,458,SUSSEX,10005,SUSSEX,10005,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
2,39-03,STATE HOUSE,REPUBLICAN,REPUBLICAN,IN-PERSON,338,SUSSEX,10005,SUSSEX,10005,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
3,39-04,STATE HOUSE,REPUBLICAN,REPUBLICAN,IN-PERSON,300,SUSSEX,10005,SUSSEX,10005,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
4,39-05,STATE HOUSE,REPUBLICAN,REPUBLICAN,IN-PERSON,544,SUSSEX,10005,SUSSEX,10005,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1

In [102]:
cols = df.columns
print(f"all columns: {cols}")

all columns: Index(['precinct', 'office', 'party_detailed', 'party_simplified', 'mode',
       'votes', 'county_name', 'county_fips', 'jurisdiction_name',
       'jurisdiction_fips', 'candidate', 'district', 'dataverse', 'year',
       'stage', 'state', 'special', 'writein', 'state_po', 'state_fips',
       'state_cen', 'state_ic', 'date', 'magnitude'],
      dtype='object')

In [103]:
df_sorted = df.sort_values(by=['county_fips', 'precinct'])
df_sorted.head()

,precinct,office,party_detailed,party_simplified,mode,votes,county_name,county_fips,jurisdiction_name,jurisdiction_fips,...,stage,state,special,writein,state_po,state_fips,state_cen,state_ic,date,magnitude
637,11-05,US SENATE,DEMOCRAT,DEMOCRAT,IN-PERSON,279,KENT,10001,KENT,10001,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
638,11-05,US SENATE,REPUBLICAN,REPUBLICAN,IN-PERSON,610,KENT,10001,KENT,10001,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
639,11-05,US SENATE,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,42,KENT,10001,KENT,10001,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
2155,11-05,KENT COUNTY CLERK OF THE PEACE,DEMOCRAT,DEMOCRAT,IN-PERSON,285,KENT,10001,KENT,10001,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1
2156,11-05,KENT COUNTY CLERK OF THE PEACE,REPUBLICAN,REPUBLICAN,IN-PERSON,634,KENT,10001,KENT,10001,...,GEN,DELAWARE,False,False,DE,10,51,11,2024-11-05,1

In [104]:
df_sorted['GEOID'] = df_sorted['county_fips'].astype(str) + "-" + df_sorted['precinct'].astype(str)

In [105]:
df_sorted.head()

,precinct,office,party_detailed,party_simplified,mode,votes,county_name,county_fips,jurisdiction_name,jurisdiction_fips,...,state,special,writein,state_po,state_fips,state_cen,state_ic,date,magnitude,GEOID
637,11-05,US SENATE,DEMOCRAT,DEMOCRAT,IN-PERSON,279,KENT,10001,KENT,10001,...,DELAWARE,False,False,DE,10,51,11,2024-11-05,1,10001-11-05
638,11-05,US SENATE,REPUBLICAN,REPUBLICAN,IN-PERSON,610,KENT,10001,KENT,10001,...,DELAWARE,False,False,DE,10,51,11,2024-11-05,1,10001-11-05
639,11-05,US SENATE,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,42,KENT,10001,KENT,10001,...,DELAWARE,False,False,DE,10,51,11,2024-11-05,1,10001-11-05
2155,11-05,KENT COUNTY CLERK OF THE PEACE,DEMOCRAT,DEMOCRAT,IN-PERSON,285,KENT,10001,KENT,10001,...,DELAWARE,False,False,DE,10,51,11,2024-11-05,1,10001-11-05
2156,11-05,KENT COUNTY CLERK OF THE PEACE,REPUBLICAN,REPUBLICAN,IN-PERSON,634,KENT,10001,KENT,10001,...,DELAWARE,False,False,DE,10,51,11,2024-11-05,1,10001-11-05

In [106]:
column_to_drop = []
for col in cols:
    unique = df_sorted[col].unique()
    if len(unique)==1:
        print(f"{col} has only 1 unique value: {unique}")
        column_to_drop.append(col)
column_to_drop.append('precinct')
column_to_drop.append('county_fips')
column_to_drop

year has only 1 unique value: [2024]
stage has only 1 unique value: ['GEN']
state has only 1 unique value: ['DELAWARE']
special has only 1 unique value: [False]
writein has only 1 unique value: [False]
state_po has only 1 unique value: ['DE']
state_fips has only 1 unique value: [10]
state_cen has only 1 unique value: [51]
state_ic has only 1 unique value: [11]
date has only 1 unique value: ['2024-11-05']
magnitude has only 1 unique value: [1]

['year',
 'stage',
 'state',
 'special',
 'writein',
 'state_po',
 'state_fips',
 'state_cen',
 'state_ic',
 'date',
 'magnitude',
 'precinct',
 'county_fips']

In [107]:
df_sorted = df_sorted.drop(column_to_drop, axis =1)

In [ ]:
cols = df_sorted.columns.tolist()
cols.remove('GEOID')
cols = ['GEOID'] + cols

df_sorted = df_sorted[cols]
df_sorted

,GEOID,office,party_detailed,party_simplified,mode,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate,district,dataverse
637,10001-11-05,US SENATE,DEMOCRAT,DEMOCRAT,IN-PERSON,279,KENT,KENT,10001,LISA BLUNT ROCHESTER,NaN,SENATE
638,10001-11-05,US SENATE,REPUBLICAN,REPUBLICAN,IN-PERSON,610,KENT,KENT,10001,ERIC HANSEN,NaN,SENATE
639,10001-11-05,US SENATE,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,42,KENT,KENT,10001,"MICHAEL ""DR MIKE"" KATZ",NaN,SENATE
2155,10001-11-05,KENT COUNTY CLERK OF THE PEACE,DEMOCRAT,DEMOCRAT,IN-PERSON,285,KENT,KENT,10001,BRENDA WOOTTEN,NaN,LOCAL
2156,10001-11-05,KENT COUNTY CLERK OF THE PEACE,REPUBLICAN,REPUBLICAN,IN-PERSON,634,KENT,KENT,10001,MARC WIENNER,NaN,LOCAL
...,...,...,...,...,...,...,...,...,...,...,...,...
41985,10005-41-16,US PRESIDENT,CONSERVATIVE,OTHER,TOTAL,0,SUSSEX,SUSSEX,10005,VERMIN SUPREME,NaN,PRESIDENT
41986,10005-41-16,US PRESIDENT,INDEPENDENT PARTY OF DELAWARE,OTHER,TOTAL,4,SUSSEX,SUSSEX,10005,ROBERT F KENNEDY,NaN,PRESIDENT
41987,10005-41-16,US PRESIDENT,LIBERTARIAN,LIBERTARIAN,TOTAL,0,SUSSEX,SUSSEX,10005,CHASE OLIVER,NaN,PRESIDENT
46237,10005-41-16,US HOUSE,DEMOCRAT,DEMOCRAT,TOTAL,169,SUSSEX,SUSSEX,10005,SARAH MCBRIDE,AT-LARGE,HOUSE
46238,10005-41-16,US HOUSE,REPUBLICAN,REPUBLICAN,TOTAL,18,SUSSEX,SUSSEX,10005,JOHN J WHALEN III,AT-LARGE,HOUSE

In [132]:
df_president = df_sorted[df_sorted['office']=='US PRESIDENT']

In [133]:
print(f"df president shape: {df_president.shape}")
candidates = df_president['candidate'].unique()
print(f"total number of candidates: {len(candidates)}")
print(f"unique candiates: {candidates}")

df president shape: (10660, 12)
total number of candidates: 5
unique candiates: ['KAMALA D HARRIS' 'DONALD J TRUMP' 'VERMIN SUPREME' 'ROBERT F KENNEDY'
 'CHASE OLIVER']

In [134]:
df_president = df_president.drop('office', axis = 1)

In [135]:
party_detailed = df_president['party_detailed'].unique()
print(f"all parties: {len(party_detailed)}")
print(party_detailed)

party_simplified = df_president['party_simplified'].unique()
print(f"all simplified parties: {len(party_simplified)}")
print(party_simplified)

all parties: 5
['DEMOCRAT' 'REPUBLICAN' 'CONSERVATIVE' 'INDEPENDENT PARTY OF DELAWARE'
 'LIBERTARIAN']
all simplified parties: 4
['DEMOCRAT' 'REPUBLICAN' 'OTHER' 'LIBERTARIAN']

In [136]:
print(f"unique county: {df_president['county_name'].unique()}")
print(f"unique jurisdiction_name: {df_president['jurisdiction_name'].unique()}")
print(f"unique jurisdictino_fips: {df_president['jurisdiction_fips'].unique()}")
print(f"unique district: {df_president['district'].unique()}")
print(f"unique dataverse: {df_president['dataverse'].unique()}")

unique county: ['KENT' 'NEW CASTLE' 'SUSSEX']
unique jurisdiction_name: ['KENT' 'NEW CASTLE' 'SUSSEX']
unique jurisdictino_fips: [10001 10003 10005]
unique district: [nan]
unique dataverse: ['PRESIDENT']

In [138]:
df_president = df_president.drop('district', axis=1)
df_president = df_president.drop('dataverse', axis = 1)

In [139]:
df_president.head()

,GEOID,party_detailed,party_simplified,mode,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate
3675,10001-11-05,DEMOCRAT,DEMOCRAT,IN-PERSON,269,KENT,KENT,10001,KAMALA D HARRIS
3676,10001-11-05,REPUBLICAN,REPUBLICAN,IN-PERSON,660,KENT,KENT,10001,DONALD J TRUMP
3677,10001-11-05,CONSERVATIVE,OTHER,IN-PERSON,1,KENT,KENT,10001,VERMIN SUPREME
3678,10001-11-05,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,15,KENT,KENT,10001,ROBERT F KENNEDY
3679,10001-11-05,LIBERTARIAN,LIBERTARIAN,IN-PERSON,3,KENT,KENT,10001,CHASE OLIVER

In [140]:
first_precicnt = df_president[df_president['GEOID']=='10001-11-05']
print(f"total first precicnt: {first_precicnt.shape}")
first_precicnt.head()

total first precicnt: (20, 9)

,GEOID,party_detailed,party_simplified,mode,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate
3675,10001-11-05,DEMOCRAT,DEMOCRAT,IN-PERSON,269,KENT,KENT,10001,KAMALA D HARRIS
3676,10001-11-05,REPUBLICAN,REPUBLICAN,IN-PERSON,660,KENT,KENT,10001,DONALD J TRUMP
3677,10001-11-05,CONSERVATIVE,OTHER,IN-PERSON,1,KENT,KENT,10001,VERMIN SUPREME
3678,10001-11-05,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,15,KENT,KENT,10001,ROBERT F KENNEDY
3679,10001-11-05,LIBERTARIAN,LIBERTARIAN,IN-PERSON,3,KENT,KENT,10001,CHASE OLIVER

In [142]:
for col in df_president.columns:
    if df_president[col].isna().any():
        print(f"NaN found in {col}")

importing NYT DE data to get the geometry boundry values

In [145]:
df_geometry = geopandas.read_file("../data/Delaware/Precinct/de_nyt.geojson")

In [146]:
df_geometry.columns

Index(['state', 'GEOID', 'votes_dem', 'votes_rep', 'votes_total',
       'pct_dem_lead', 'official_boundary', 'geometry'],
      dtype='object')

In [147]:
needed_cols = ['GEOID', 'geometry']
df_geometry = df_geometry[needed_cols]
df_geometry

           GEOID                                           geometry
0    10001-11-05  POLYGON ((-75.6658 39.29057, -75.66581 39.2905...
1    10001-11-06  POLYGON ((-75.75449 39.22743, -75.75449 39.227...
2    10001-11-07  POLYGON ((-75.69349 39.19968, -75.6935 39.1996...
3    10001-11-08  POLYGON ((-75.64732 39.15437, -75.64734 39.154...
4    10001-11-09  POLYGON ((-75.74776 39.14335, -75.74776 39.143...
..           ...                                                ...
521  10005-41-11  POLYGON ((-75.19192 38.47895, -75.19193 38.478...
522  10005-41-12  POLYGON ((-75.18948 38.48168, -75.18857 38.482...
523  10005-41-13  POLYGON ((-75.19192 38.47895, -75.19191 38.478...
524  10005-41-14  POLYGON ((-75.17737 38.53138, -75.17696 38.531...
525  10005-20-13  POLYGON ((-75.06412 38.87434, -75.06803 38.870...

[526 rows x 2 columns]

In [149]:
len(df_geometry['GEOID'].unique())

526

merging by **GEOID**

In [150]:
df_merged = df_president.merge(
    df_geometry[['GEOID', 'geometry']],
    on='GEOID',
    how='left'
)

In [151]:
df_merged

,GEOID,party_detailed,party_simplified,mode,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate,geometry
0,10001-11-05,DEMOCRAT,DEMOCRAT,IN-PERSON,269,KENT,KENT,10001,KAMALA D HARRIS,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
1,10001-11-05,REPUBLICAN,REPUBLICAN,IN-PERSON,660,KENT,KENT,10001,DONALD J TRUMP,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
2,10001-11-05,CONSERVATIVE,OTHER,IN-PERSON,1,KENT,KENT,10001,VERMIN SUPREME,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
3,10001-11-05,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,15,KENT,KENT,10001,ROBERT F KENNEDY,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
4,10001-11-05,LIBERTARIAN,LIBERTARIAN,IN-PERSON,3,KENT,KENT,10001,CHASE OLIVER,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
...,...,...,...,...,...,...,...,...,...,...
10655,10005-41-16,DEMOCRAT,DEMOCRAT,TOTAL,172,SUSSEX,SUSSEX,10005,KAMALA D HARRIS,None
10656,10005-41-16,REPUBLICAN,REPUBLICAN,TOTAL,12,SUSSEX,SUSSEX,10005,DONALD J TRUMP,None
10657,10005-41-16,CONSERVATIVE,OTHER,TOTAL,0,SUSSEX,SUSSEX,10005,VERMIN SUPREME,None
10658,10005-41-16,INDEPENDENT PARTY OF DELAWARE,OTHER,TOTAL,4,SUSSEX,SUSSEX,10005,ROBERT F KENNEDY,None
10659,10005-41-16,LIBERTARIAN,LIBERTARIAN,TOTAL,0,SUSSEX,SUSSEX,10005,CHASE OLIVER,None

In [155]:
total_unique = df_merged['GEOID'].unique()
print(f"total num of precinct: {len(total_unique)}")

total num of precinct: 533

In [153]:
missing_geometry = df_merged.loc[
    df_merged['geometry'].isna(),
    'GEOID'
].unique()

print(f"total missing geometry: {len(missing_geometry)}")
print(f"IDS: {missing_geometry}")

total missing geometry: 7
IDS: ['10001-31-16' '10001-31-17' '10001-41-17' '10003-02-27' '10003-02-28'
 '10003-17-14' '10005-41-16']

In [164]:
missing1 = df_merged[df_merged['GEOID']=='10005-41-16']
missing1

,GEOID,party_detailed,party_simplified,mode,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate,geometry
10640,10005-41-16,DEMOCRAT,DEMOCRAT,IN-PERSON,0,SUSSEX,SUSSEX,10005,KAMALA D HARRIS,None
10641,10005-41-16,REPUBLICAN,REPUBLICAN,IN-PERSON,0,SUSSEX,SUSSEX,10005,DONALD J TRUMP,None
10642,10005-41-16,CONSERVATIVE,OTHER,IN-PERSON,0,SUSSEX,SUSSEX,10005,VERMIN SUPREME,None
10643,10005-41-16,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,0,SUSSEX,SUSSEX,10005,ROBERT F KENNEDY,None
10644,10005-41-16,LIBERTARIAN,LIBERTARIAN,IN-PERSON,0,SUSSEX,SUSSEX,10005,CHASE OLIVER,None
10645,10005-41-16,DEMOCRAT,DEMOCRAT,ABSENTEE,172,SUSSEX,SUSSEX,10005,KAMALA D HARRIS,None
10646,10005-41-16,REPUBLICAN,REPUBLICAN,ABSENTEE,12,SUSSEX,SUSSEX,10005,DONALD J TRUMP,None
10647,10005-41-16,CONSERVATIVE,OTHER,ABSENTEE,0,SUSSEX,SUSSEX,10005,VERMIN SUPREME,None
10648,10005-41-16,INDEPENDENT PARTY OF DELAWARE,OTHER,ABSENTEE,4,SUSSEX,SUSSEX,10005,ROBERT F KENNEDY,None
10649,10005-41-16,LIBERTARIAN,LIBERTARIAN,ABSENTEE,0,SUSSEX,SUSSEX,10005,CHASE OLIVER,None
10650,10005-41-16,DEMOCRAT,DEMOCRAT,EARLY,0,SUSSEX,SUSSEX,10005,KAMALA D HARRIS,None
10651,10005-41-16,REPUBLICAN,REPUBLICAN,EARLY,0,SUSSEX,SUSSEX,10005,DONALD J TRUMP,None
10652,10005-41-16,CONSERVATIVE,OTHER,EARLY,0,SUSSEX,SUSSEX,10005,VERMIN SUPREME,None
10653,10005-41-16,INDEPENDENT PARTY OF DELAWARE,OTHER,EARLY,0,SUSSEX,SUSSEX,10005,ROBERT F KENNEDY,None
10654,10005-41-16,LIBERTARIAN,LIBERTARIAN,EARLY,0,SUSSEX,SUSSEX,10005,CHASE OLIVER,None
10655,10005-41-16,DEMOCRAT,DEMOCRAT,TOTAL,172,SUSSEX,SUSSEX,10005,KAMALA D HARRIS,None
10656,10005-41-16,REPUBLICAN,REPUBLICAN,TOTAL,12,SUSSEX,SUSSEX,10005,DONALD J TRUMP,None
10657,10005-41-16,CONSERVATIVE,OTHER,TOTAL,0,SUSSEX,SUSSEX,10005,VERMIN SUPREME,None
10658,10005-41-16,INDEPENDENT PARTY OF DELAWARE,OTHER,TOTAL,4,SUSSEX,SUSSEX,10005,ROBERT F KENNEDY,None
10659,10005-41-16,LIBERTARIAN,LIBERTARIAN,TOTAL,0,SUSSEX,SUSSEX,10005,CHASE OLIVER,None

remove all the precinct without geometry (they don't have any voting infos either all 0 or absentee)

In [165]:
df_merged = df_merged[df_merged['geometry'].notna()]
missing_geometry = df_merged.loc[
    df_merged['geometry'].isna(),
    'GEOID'
].unique()

print(f"total missing geometry: {len(missing_geometry)}")
print(f"IDS: {missing_geometry}")

total missing geometry: 0
IDS: []

In [166]:
first_precicnt = df_merged[df_merged['GEOID']=='10001-11-05']
first_precicnt

,GEOID,party_detailed,party_simplified,mode,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate,geometry
0,10001-11-05,DEMOCRAT,DEMOCRAT,IN-PERSON,269,KENT,KENT,10001,KAMALA D HARRIS,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
1,10001-11-05,REPUBLICAN,REPUBLICAN,IN-PERSON,660,KENT,KENT,10001,DONALD J TRUMP,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
2,10001-11-05,CONSERVATIVE,OTHER,IN-PERSON,1,KENT,KENT,10001,VERMIN SUPREME,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
3,10001-11-05,INDEPENDENT PARTY OF DELAWARE,OTHER,IN-PERSON,15,KENT,KENT,10001,ROBERT F KENNEDY,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
4,10001-11-05,LIBERTARIAN,LIBERTARIAN,IN-PERSON,3,KENT,KENT,10001,CHASE OLIVER,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
5,10001-11-05,DEMOCRAT,DEMOCRAT,ABSENTEE,54,KENT,KENT,10001,KAMALA D HARRIS,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
6,10001-11-05,REPUBLICAN,REPUBLICAN,ABSENTEE,46,KENT,KENT,10001,DONALD J TRUMP,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
7,10001-11-05,CONSERVATIVE,OTHER,ABSENTEE,1,KENT,KENT,10001,VERMIN SUPREME,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
8,10001-11-05,INDEPENDENT PARTY OF DELAWARE,OTHER,ABSENTEE,0,KENT,KENT,10001,ROBERT F KENNEDY,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
9,10001-11-05,LIBERTARIAN,LIBERTARIAN,ABSENTEE,0,KENT,KENT,10001,CHASE OLIVER,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
10,10001-11-05,DEMOCRAT,DEMOCRAT,EARLY,198,KENT,KENT,10001,KAMALA D HARRIS,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
11,10001-11-05,REPUBLICAN,REPUBLICAN,EARLY,410,KENT,KENT,10001,DONALD J TRUMP,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
12,10001-11-05,CONSERVATIVE,OTHER,EARLY,0,KENT,KENT,10001,VERMIN SUPREME,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
13,10001-11-05,INDEPENDENT PARTY OF DELAWARE,OTHER,EARLY,6,KENT,KENT,10001,ROBERT F KENNEDY,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
14,10001-11-05,LIBERTARIAN,LIBERTARIAN,EARLY,2,KENT,KENT,10001,CHASE OLIVER,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
15,10001-11-05,DEMOCRAT,DEMOCRAT,TOTAL,521,KENT,KENT,10001,KAMALA D HARRIS,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
16,10001-11-05,REPUBLICAN,REPUBLICAN,TOTAL,1116,KENT,KENT,10001,DONALD J TRUMP,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
17,10001-11-05,CONSERVATIVE,OTHER,TOTAL,2,KENT,KENT,10001,VERMIN SUPREME,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
18,10001-11-05,INDEPENDENT PARTY OF DELAWARE,OTHER,TOTAL,21,KENT,KENT,10001,ROBERT F KENNEDY,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."
19,10001-11-05,LIBERTARIAN,LIBERTARIAN,TOTAL,5,KENT,KENT,10001,CHASE OLIVER,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905..."

In [ ]:
df_merged = df_merged.drop('party_detailed', axis = 1)