In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import zipfile

### SeaWulf data prep (Election + Demographic by Precincts)

#### Estimated Population from ACS
- no geometry + precicnts information

In [2]:
zip_path = "../data/Georgia/CVAP_2020_2024_ASC.zip"

with zipfile.ZipFile(zip_path) as z:
    print(z.namelist())
    with z.open("BlockGr.csv") as f:
        cvap_df = pd.read_csv(f)

cvap_df.head()

['BlockGr.csv', 'CD.csv', 'County.csv', 'MCD.csv', 'Nation.csv', 'Place.csv', 'SLDLC.csv', 'SLDUC.csv', 'State.csv', 'Tract.csv', 'CVAP_2020-2024_ACS_documentation_v1.pdf']

,geoname,lntitle,geoid,lnnumber,cit_est,cit_moe,cvap_est,cvap_moe
0,"Block Group 1, Census Tract 201, Autauga Count...",Total,1500000US010010201001,1,486,149,409,103
1,"Block Group 1, Census Tract 201, Autauga Count...",Not Hispanic or Latino,1500000US010010201001,2,444,131,391,106
2,"Block Group 1, Census Tract 201, Autauga Count...",American Indian or Alaska Native Alone,1500000US010010201001,3,0,13,0,13
3,"Block Group 1, Census Tract 201, Autauga Count...",Asian Alone,1500000US010010201001,4,0,13,0,13
4,"Block Group 1, Census Tract 201, Autauga Count...",Black or African American Alone,1500000US010010201001,5,7,6,0,13

In [3]:
ga_blocks = cvap_df[cvap_df['geoid'].str.startswith("1500000US13")]
ga_blocks

,geoname,lntitle,geoid,lnnumber,cit_est,cit_moe,cvap_est,cvap_moe
761059,"Block Group 1, Census Tract 9501, Appling Coun...",Total,1500000US130019501001,1,1020,317,839,246
761060,"Block Group 1, Census Tract 9501, Appling Coun...",Not Hispanic or Latino,1500000US130019501001,2,956,300,778,235
761061,"Block Group 1, Census Tract 9501, Appling Coun...",American Indian or Alaska Native Alone,1500000US130019501001,3,0,14,0,14
761062,"Block Group 1, Census Tract 9501, Appling Coun...",Asian Alone,1500000US130019501001,4,0,14,0,14
761063,"Block Group 1, Census Tract 9501, Appling Coun...",Black or African American Alone,1500000US130019501001,5,34,34,28,33
...,...,...,...,...,...,...,...,...
857852,"Block Group 2, Census Tract 9506, Worth County...",Asian and White,1500000US133219506002,9,0,14,0,14
857853,"Block Group 2, Census Tract 9506, Worth County...",Black or African American and White,1500000US133219506002,10,16,18,7,8
857854,"Block Group 2, Census Tract 9506, Worth County...",American Indian or Alaska Native and Black or ...,1500000US133219506002,11,0,14,0,14
857855,"Block Group 2, Census Tract 9506, Worth County...",Remainder of Two or More Race Responses,1500000US133219506002,12,0,14,0,14
857856,"Block Group 2, Census Tract 9506, Worth County...",Hispanic or Latino,1500000US133219506002,13,0,14,0,14

In [4]:
ga_blocks.columns

Index(['geoname', 'lntitle', 'geoid', 'lnnumber', 'cit_est', 'cit_moe',
       'cvap_est', 'cvap_moe'],
      dtype='str')

In [5]:
zip_path = "../data/Georgia/TIGER_shape.zip"

tiger_block = gpd.read_file(
    f"zip://{zip_path}!tl_2021_13_bg.shp"
)

print(tiger_block.shape)
tiger_block.head()

(7446, 13)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,GEOID,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,13,089,021405,1,130890214051,Block Group 1,G5030,S,862271,0,+33.8595904,-084.3195696,"POLYGON ((-84.3265 33.86164, -84.32584 33.8616..."
1,13,121,011647,2,131210116472,Block Group 2,G5030,S,1945049,4158,+34.0631301,-084.3193902,"POLYGON ((-84.33576 34.07, -84.3353 34.07006, ..."
2,13,121,011647,3,131210116473,Block Group 3,G5030,S,2306047,16644,+34.0504935,-084.3120946,"POLYGON ((-84.32848 34.04942, -84.32663 34.049..."
3,13,121,011643,3,131210116433,Block Group 3,G5030,S,1996441,7422,+34.0964538,-084.2624178,"POLYGON ((-84.27867 34.09433, -84.27866 34.094..."
4,13,121,011640,2,131210116402,Block Group 2,G5030,S,1474698,1087,+34.0721558,-084.2879233,"POLYGON ((-84.29667 34.07128, -84.29546 34.072..."

In [6]:
tiger_block.columns

Index(['STATEFP', 'COUNTYFP', 'TRACTCE', 'BLKGRPCE', 'GEOID', 'NAMELSAD',
       'MTFCC', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON',
       'geometry'],
      dtype='str')

In [7]:
tiger_col = ['GEOID', 'geometry']
tiger_block = tiger_block[tiger_col]

In [8]:
ga_blocks['clean_GEOID'] = ga_blocks['geoid'].str.replace("1500000US", "")
ga_blocks.head()

,geoname,lntitle,geoid,lnnumber,cit_est,cit_moe,cvap_est,cvap_moe,clean_GEOID
761059,"Block Group 1, Census Tract 9501, Appling Coun...",Total,1500000US130019501001,1,1020,317,839,246,130019501001
761060,"Block Group 1, Census Tract 9501, Appling Coun...",Not Hispanic or Latino,1500000US130019501001,2,956,300,778,235,130019501001
761061,"Block Group 1, Census Tract 9501, Appling Coun...",American Indian or Alaska Native Alone,1500000US130019501001,3,0,14,0,14,130019501001
761062,"Block Group 1, Census Tract 9501, Appling Coun...",Asian Alone,1500000US130019501001,4,0,14,0,14,130019501001
761063,"Block Group 1, Census Tract 9501, Appling Coun...",Black or African American Alone,1500000US130019501001,5,34,34,28,33,130019501001

In [9]:
clean_id = ga_blocks['clean_GEOID']
org_id = ga_blocks['geoid']
geoid20 = tiger_block['GEOID']
print(f"unique org_id len: {len(org_id.unique())}")
print(f"unique clean_id len: {len(clean_id.unique())}")
print(f"tiger len: {len(geoid20)}")
print(len(set(ga_blocks["clean_GEOID"]) & set(tiger_block["GEOID"])))

unique org_id len: 7446
unique clean_id len: 7446
tiger len: 7446
7446

In [10]:
merged_block = ga_blocks.merge(
    tiger_block,
    left_on="clean_GEOID",
    right_on="GEOID",
    how="left"
)
merged_block.head()

,geoname,lntitle,geoid,lnnumber,cit_est,cit_moe,cvap_est,cvap_moe,clean_GEOID,GEOID,geometry
0,"Block Group 1, Census Tract 9501, Appling Coun...",Total,1500000US130019501001,1,1020,317,839,246,130019501001,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
1,"Block Group 1, Census Tract 9501, Appling Coun...",Not Hispanic or Latino,1500000US130019501001,2,956,300,778,235,130019501001,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
2,"Block Group 1, Census Tract 9501, Appling Coun...",American Indian or Alaska Native Alone,1500000US130019501001,3,0,14,0,14,130019501001,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
3,"Block Group 1, Census Tract 9501, Appling Coun...",Asian Alone,1500000US130019501001,4,0,14,0,14,130019501001,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
4,"Block Group 1, Census Tract 9501, Appling Coun...",Black or African American Alone,1500000US130019501001,5,34,34,28,33,130019501001,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."

In [11]:
print(merged_block.shape)
print(f"null geometry: {merged_block['geometry'].isna().sum()}")

(96798, 11)
null geometry: 0

In [12]:
remove_col_block = ['geoid', 'clean_GEOID']
merged_block = merged_block.drop(columns=remove_col_block)
merged_block.head()

,geoname,lntitle,lnnumber,cit_est,cit_moe,cvap_est,cvap_moe,GEOID,geometry
0,"Block Group 1, Census Tract 9501, Appling Coun...",Total,1,1020,317,839,246,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
1,"Block Group 1, Census Tract 9501, Appling Coun...",Not Hispanic or Latino,2,956,300,778,235,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
2,"Block Group 1, Census Tract 9501, Appling Coun...",American Indian or Alaska Native Alone,3,0,14,0,14,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
3,"Block Group 1, Census Tract 9501, Appling Coun...",Asian Alone,4,0,14,0,14,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
4,"Block Group 1, Census Tract 9501, Appling Coun...",Black or African American Alone,5,34,34,28,33,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."

In [13]:
merged_block['lntitle'].unique()

<StringArray>
[                                                         'Total',
                                         'Not Hispanic or Latino',
                         'American Indian or Alaska Native Alone',
                                                    'Asian Alone',
                                'Black or African American Alone',
                'Native Hawaiian or Other Pacific Islander Alone',
                                                    'White Alone',
                     'American Indian or Alaska Native and White',
                                                'Asian and White',
                            'Black or African American and White',
 'American Indian or Alaska Native and Black or African American',
                        'Remainder of Two or More Race Responses',
                                             'Hispanic or Latino']
Length: 13, dtype: str

Population breakdown:
- Total: ['Total']
- White: ['White Alone']
- Black: ['Black or African American Alone']
- Latino: ['Hispanic or Latino']
- Other: ['American Indian or Alaska Native Alone', 'Asian Alone', 'Native Hawaiian or Other Pacific Islander Alone', 'American Indian or Alaska Native and White', 'Asian and White', 'Black or African American and White','American Indian or Alaska Native and Black or African American',
       'Remainder of Two or More Race Responses',]

In [14]:
category_map = {
    "Total": ["Total"],
    "White": ["White Alone"],
    "Black": ["Black or African American Alone"],
    "Latino": ["Hispanic or Latino"],
    "Other": [
        "American Indian or Alaska Native Alone",
        "Asian Alone",
        "Native Hawaiian or Other Pacific Islander Alone",
        "American Indian or Alaska Native and White",
        "Asian and White",
        "Black or African American and White",
        "American Indian or Alaska Native and Black or African American",
        "Remainder of Two or More Race Responses"
    ]
}

reverse_map = {}
for new_cat, old_list in category_map.items():
    for old in old_list:
        reverse_map[old] = new_cat
        
reverse_map

{'Total': 'Total',
 'White Alone': 'White',
 'Black or African American Alone': 'Black',
 'Hispanic or Latino': 'Latino',
 'American Indian or Alaska Native Alone': 'Other',
 'Asian Alone': 'Other',
 'Native Hawaiian or Other Pacific Islander Alone': 'Other',
 'American Indian or Alaska Native and White': 'Other',
 'Asian and White': 'Other',
 'Black or African American and White': 'Other',
 'American Indian or Alaska Native and Black or African American': 'Other',
 'Remainder of Two or More Race Responses': 'Other'}

In [15]:
merged_block['racial_category'] = merged_block["lntitle"].map(reverse_map)
merged_block = merged_block[merged_block['racial_category'].notna()]
merged_block.head()

,geoname,lntitle,lnnumber,cit_est,cit_moe,cvap_est,cvap_moe,GEOID,geometry,racial_category
0,"Block Group 1, Census Tract 9501, Appling Coun...",Total,1,1020,317,839,246,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861...",Total
2,"Block Group 1, Census Tract 9501, Appling Coun...",American Indian or Alaska Native Alone,3,0,14,0,14,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861...",Other
3,"Block Group 1, Census Tract 9501, Appling Coun...",Asian Alone,4,0,14,0,14,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861...",Other
4,"Block Group 1, Census Tract 9501, Appling Coun...",Black or African American Alone,5,34,34,28,33,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861...",Black
5,"Block Group 1, Census Tract 9501, Appling Coun...",Native Hawaiian or Other Pacific Islander Alone,6,0,14,0,14,130019501001,"POLYGON ((-82.43165 31.85615, -82.43158 31.861...",Other

In [16]:
grouped = merged_block.groupby(["GEOID", "racial_category"]).agg({
    "cvap_est": "sum"
}).reset_index()

In [17]:
grouped.head()

          GEOID racial_category  cvap_est
0  130019501001           Black        28
1  130019501001          Latino        61
2  130019501001           Other         0
3  130019501001           Total       839
4  130019501001           White       750

In [18]:
wide = grouped.pivot(index="GEOID", columns="racial_category", values="cvap_est").reset_index()

In [19]:
geo = merged_block[["GEOID", "geometry"]].drop_duplicates()

final_df = wide.merge(geo, on="GEOID")

In [20]:
columns_order = ['GEOID', 'White', 'Black','Latino','Other','Total','geometry']
final_df = final_df[columns_order]
print(final_df.shape)
final_df.head()

(7446, 7)

,GEOID,White,Black,Latino,Other,Total,geometry
0,130019501001,750,28,61,0,839,"POLYGON ((-82.43165 31.85615, -82.43158 31.861..."
1,130019501002,194,0,143,0,337,"POLYGON ((-82.26715 31.85504, -82.2665 31.8553..."
2,130019501003,872,171,0,8,1051,"POLYGON ((-82.35646 31.85798, -82.35642 31.862..."
3,130019502011,520,260,22,22,824,"POLYGON ((-82.3328 31.78873, -82.33213 31.7891..."
4,130019502012,766,85,0,0,851,"POLYGON ((-82.35209 31.84147, -82.35145 31.841..."

In [21]:
final_total = (final_df['White'] + final_df['Black'] + final_df['Latino'] + final_df['Other'])
diffs = final_df["Total"] - final_total
print(f"diff in total and sum population: {(diffs != 0).any()}")

diff in total and sum population: False

#### Precicnt boundaries + 2024 Election Results from US Census

In [22]:
zip_path = "../data/Georgia/GA24_general_election.zip"

precincts_df = gpd.read_file(
    f"zip://{zip_path}!ga_2024_gen_all_prec/ga_2024_gen_all_prec.shp"
)

print(precincts_df.shape)
precincts_df.head()

(2720, 395)

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,G24A1NO,G24A1YES,G24A2NO,G24A2YES,G24RFANO,...,GSL175DWIS,GSL175RLAH,GSL176RBUR,GSL177DSHA,GSL177RGRI,GSL178RMEE,GSL179RTOW,GSL180DDAN,GSL180RSAI,geometry
0,APPLING-:-1B,001,Appling,1B,1B,400,515,553,356,452,...,0,0,0,0,0,0,0,0,0,"POLYGON ((375680.672 3535246.721, 375706.51 35..."
1,APPLING-:-1C,001,Appling,1C,1C,324,400,428,284,356,...,0,0,0,0,0,115,0,0,0,"POLYGON ((378693.089 3524550.847, 378692.833 3..."
2,APPLING-:-2,001,Appling,2,2,487,669,626,516,668,...,0,0,0,0,0,0,0,0,0,"POLYGON ((380005.78 3525000.183, 380113.838 35..."
3,APPLING-:-3A1,001,Appling,3A1,3A1,240,351,344,238,271,...,0,0,0,0,0,0,0,0,0,"POLYGON ((377772.229 3534595.104, 377753.854 3..."
4,APPLING-:-3C,001,Appling,3C,3C,439,596,577,444,509,...,0,0,0,0,0,70,0,0,0,"POLYGON ((386430.887 3520109.322, 386469.241 3..."

wants columns that started with **G24PRE**

In [23]:
columns = precincts_df.columns
pres_col = [col for col in columns if col.startswith("G24PRE")]
basic_col = ['UNIQUE_ID', 'COUNTYFP', 'County', 'PRECINCT_I', 'PRECINCT_N','geometry']
all_col = basic_col + pres_col
all_col

['UNIQUE_ID',
 'COUNTYFP',
 'County',
 'PRECINCT_I',
 'PRECINCT_N',
 'geometry',
 'G24PREDHAR',
 'G24PREGSTE',
 'G24PREICRU',
 'G24PREIWES',
 'G24PRELOLI',
 'G24PRERTRU']

In [24]:
filtered_precicnts = precincts_df[all_col]
print(filtered_precicnts.shape)
filtered_precicnts.head()

(2720, 12)

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,geometry,G24PREDHAR,G24PREGSTE,G24PREICRU,G24PREIWES,G24PRELOLI,G24PRERTRU
0,APPLING-:-1B,001,Appling,1B,1B,"POLYGON ((375680.672 3535246.721, 375706.51 35...",108,0,0,0,2,921
1,APPLING-:-1C,001,Appling,1C,1C,"POLYGON ((378693.089 3524550.847, 378692.833 3...",67,0,0,0,0,724
2,APPLING-:-2,001,Appling,2,2,"POLYGON ((380005.78 3525000.183, 380113.838 35...",782,3,0,0,1,541
3,APPLING-:-3A1,001,Appling,3A1,3A1,"POLYGON ((377772.229 3534595.104, 377753.854 3...",31,0,0,0,0,617
4,APPLING-:-3C,001,Appling,3C,3C,"POLYGON ((386430.887 3520109.322, 386469.241 3...",246,0,0,0,3,934

In [25]:
other_pres = ['G24PREGSTE', 'G24PREICRU', 'G24PREIWES','G24PRELOLI']
filtered_precicnts['Other_candidates'] = filtered_precicnts[other_pres].sum(axis=1)
filtered_precicnts.head()

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,geometry,G24PREDHAR,G24PREGSTE,G24PREICRU,G24PREIWES,G24PRELOLI,G24PRERTRU,Other_candidates
0,APPLING-:-1B,001,Appling,1B,1B,"POLYGON ((375680.672 3535246.721, 375706.51 35...",108,0,0,0,2,921,2
1,APPLING-:-1C,001,Appling,1C,1C,"POLYGON ((378693.089 3524550.847, 378692.833 3...",67,0,0,0,0,724,0
2,APPLING-:-2,001,Appling,2,2,"POLYGON ((380005.78 3525000.183, 380113.838 35...",782,3,0,0,1,541,4
3,APPLING-:-3A1,001,Appling,3A1,3A1,"POLYGON ((377772.229 3534595.104, 377753.854 3...",31,0,0,0,0,617,0
4,APPLING-:-3C,001,Appling,3C,3C,"POLYGON ((386430.887 3520109.322, 386469.241 3...",246,0,0,0,3,934,3

In [26]:
filtered_precicnts = filtered_precicnts.drop(columns=other_pres)
filtered_precicnts.head()

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,geometry,G24PREDHAR,G24PRERTRU,Other_candidates
0,APPLING-:-1B,001,Appling,1B,1B,"POLYGON ((375680.672 3535246.721, 375706.51 35...",108,921,2
1,APPLING-:-1C,001,Appling,1C,1C,"POLYGON ((378693.089 3524550.847, 378692.833 3...",67,724,0
2,APPLING-:-2,001,Appling,2,2,"POLYGON ((380005.78 3525000.183, 380113.838 35...",782,541,4
3,APPLING-:-3A1,001,Appling,3A1,3A1,"POLYGON ((377772.229 3534595.104, 377753.854 3...",31,617,0
4,APPLING-:-3C,001,Appling,3C,3C,"POLYGON ((386430.887 3520109.322, 386469.241 3...",246,934,3

In [27]:
rename_pres = {'G24PREDHAR': 'Kamala D. Harris', 'G24PRERTRU': 'Donald J. Trump'}
filtered_precicnts = filtered_precicnts.rename(columns = rename_pres)
filtered_precicnts.head()

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,geometry,Kamala D. Harris,Donald J. Trump,Other_candidates
0,APPLING-:-1B,001,Appling,1B,1B,"POLYGON ((375680.672 3535246.721, 375706.51 35...",108,921,2
1,APPLING-:-1C,001,Appling,1C,1C,"POLYGON ((378693.089 3524550.847, 378692.833 3...",67,724,0
2,APPLING-:-2,001,Appling,2,2,"POLYGON ((380005.78 3525000.183, 380113.838 35...",782,541,4
3,APPLING-:-3A1,001,Appling,3A1,3A1,"POLYGON ((377772.229 3534595.104, 377753.854 3...",31,617,0
4,APPLING-:-3C,001,Appling,3C,3C,"POLYGON ((386430.887 3520109.322, 386469.241 3...",246,934,3

#### Merging block based estimated population w. 2024 election precicnts
- `all_df` = contains block-level population estimate w. block geometry
- `filtered_precicnts` = contains precicnts-level election results w. precicnts geometry

In [28]:
precincts = gpd.GeoDataFrame(filtered_precicnts, geometry="geometry")
blocks = gpd.GeoDataFrame(final_df, geometry="geometry")

In [29]:
# change to CRS for blocks / was orignally in GPS
blocks = blocks.to_crs(precincts.crs)

In [30]:
intersection = gpd.overlay(blocks, precincts, how="intersection")

In [31]:
intersection["area"] = intersection.geometry.area
blocks["block_area"] = blocks.geometry.area
intersection = intersection.merge(
    blocks[["GEOID", "block_area"]],
    on="GEOID"
)

intersection["weight"] = intersection["area"] / intersection["block_area"]

In [32]:
for col in ["White", "Black", "Latino", "Other", "Total"]:
    intersection[f"{col}_population"] = intersection[col] * intersection["weight"]

In [33]:
precinct_demo = intersection.groupby("UNIQUE_ID").agg({
    "White_population": "sum",
    "Black_population": "sum",
    "Latino_population": "sum",
    "Other_population": "sum",
    "Total_population": "sum"
}).reset_index()

In [34]:
final_precincts = precincts.merge(precinct_demo, on="UNIQUE_ID")

In [35]:
final_precincts.head()

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,geometry,Kamala D. Harris,Donald J. Trump,Other_candidates,White_population,Black_population,Latino_population,Other_population,Total_population
0,APPLING-:-1B,001,Appling,1B,1B,"POLYGON ((375680.672 3535246.721, 375706.51 35...",108,921,2,1074.216588,102.982480,55.003760,3.618320,1235.821148
1,APPLING-:-1C,001,Appling,1C,1C,"POLYGON ((378693.089 3524550.847, 378692.833 3...",67,724,0,1191.912651,472.673690,42.287709,28.713142,1735.587191
2,APPLING-:-2,001,Appling,2,2,"POLYGON ((380005.78 3525000.183, 380113.838 35...",782,541,4,1235.612665,788.224243,96.849558,32.601383,2153.287850
3,APPLING-:-3A1,001,Appling,3A1,3A1,"POLYGON ((377772.229 3534595.104, 377753.854 3...",31,617,0,705.543285,121.434717,146.434231,7.825296,981.237529
4,APPLING-:-3C,001,Appling,3C,3C,"POLYGON ((386430.887 3520109.322, 386469.241 3...",246,934,3,1427.934442,416.186300,57.464584,60.117966,1961.703292

In [36]:
final_precincts['Total_votes'] = final_precincts['Kamala D. Harris'] + final_precincts['Donald J. Trump'] 
+ final_precincts['Other_candidates']
final_precincts.head()

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,geometry,Kamala D. Harris,Donald J. Trump,Other_candidates,White_population,Black_population,Latino_population,Other_population,Total_population,Total_votes
0,APPLING-:-1B,001,Appling,1B,1B,"POLYGON ((375680.672 3535246.721, 375706.51 35...",108,921,2,1074.216588,102.982480,55.003760,3.618320,1235.821148,1029
1,APPLING-:-1C,001,Appling,1C,1C,"POLYGON ((378693.089 3524550.847, 378692.833 3...",67,724,0,1191.912651,472.673690,42.287709,28.713142,1735.587191,791
2,APPLING-:-2,001,Appling,2,2,"POLYGON ((380005.78 3525000.183, 380113.838 35...",782,541,4,1235.612665,788.224243,96.849558,32.601383,2153.287850,1323
3,APPLING-:-3A1,001,Appling,3A1,3A1,"POLYGON ((377772.229 3534595.104, 377753.854 3...",31,617,0,705.543285,121.434717,146.434231,7.825296,981.237529,648
4,APPLING-:-3C,001,Appling,3C,3C,"POLYGON ((386430.887 3520109.322, 386469.241 3...",246,934,3,1427.934442,416.186300,57.464584,60.117966,1961.703292,1180

In [37]:
state_total_votes = final_precincts['Total_votes'].sum()
total_population = final_precincts['Total_population'].sum()

print(f"total pop: {total_population}, total votes: {state_total_votes}")

org_total_pop = final_df['Total'].sum()
print(f"original total pop block level: {org_total_pop}")
print(f"difference between block + precicnts: {org_total_pop - total_population}")

total pop: 7834440.536300911, total votes: 5211134
original total pop block level: 7834506
difference between block + precicnts: 65.46369908936322

In [38]:
final_precincts.columns

Index(['UNIQUE_ID', 'COUNTYFP', 'County', 'PRECINCT_I', 'PRECINCT_N',
       'geometry', 'Kamala D. Harris', 'Donald J. Trump', 'Other_candidates',
       'White_population', 'Black_population', 'Latino_population',
       'Other_population', 'Total_population', 'Total_votes'],
      dtype='str')

In [39]:
reorder_columns = ['UNIQUE_ID', 'COUNTYFP', 'County', 'PRECINCT_I', 'PRECINCT_N',
        'Kamala D. Harris', 'Donald J. Trump', 'Other_candidates', 'Total_votes',
       'White_population', 'Black_population', 'Latino_population', 'Other_population',
       'Total_population', 'geometry']

In [40]:
final_precincts = final_precincts[reorder_columns]
final_precincts.head()

,UNIQUE_ID,COUNTYFP,County,PRECINCT_I,PRECINCT_N,Kamala D. Harris,Donald J. Trump,Other_candidates,Total_votes,White_population,Black_population,Latino_population,Other_population,Total_population,geometry
0,APPLING-:-1B,001,Appling,1B,1B,108,921,2,1029,1074.216588,102.982480,55.003760,3.618320,1235.821148,"POLYGON ((375680.672 3535246.721, 375706.51 35..."
1,APPLING-:-1C,001,Appling,1C,1C,67,724,0,791,1191.912651,472.673690,42.287709,28.713142,1735.587191,"POLYGON ((378693.089 3524550.847, 378692.833 3..."
2,APPLING-:-2,001,Appling,2,2,782,541,4,1323,1235.612665,788.224243,96.849558,32.601383,2153.287850,"POLYGON ((380005.78 3525000.183, 380113.838 35..."
3,APPLING-:-3A1,001,Appling,3A1,3A1,31,617,0,648,705.543285,121.434717,146.434231,7.825296,981.237529,"POLYGON ((377772.229 3534595.104, 377753.854 3..."
4,APPLING-:-3C,001,Appling,3C,3C,246,934,3,1180,1427.934442,416.186300,57.464584,60.117966,1961.703292,"POLYGON ((386430.887 3520109.322, 386469.241 3..."

In [41]:
drop_col = ['COUNTYFP',	'County', 'PRECINCT_I',	'PRECINCT_N']
final_precincts = final_precincts.drop(columns=drop_col)
final_precincts.head()

,UNIQUE_ID,Kamala D. Harris,Donald J. Trump,Other_candidates,Total_votes,White_population,Black_population,Latino_population,Other_population,Total_population,geometry
0,APPLING-:-1B,108,921,2,1029,1074.216588,102.982480,55.003760,3.618320,1235.821148,"POLYGON ((375680.672 3535246.721, 375706.51 35..."
1,APPLING-:-1C,67,724,0,791,1191.912651,472.673690,42.287709,28.713142,1735.587191,"POLYGON ((378693.089 3524550.847, 378692.833 3..."
2,APPLING-:-2,782,541,4,1323,1235.612665,788.224243,96.849558,32.601383,2153.287850,"POLYGON ((380005.78 3525000.183, 380113.838 35..."
3,APPLING-:-3A1,31,617,0,648,705.543285,121.434717,146.434231,7.825296,981.237529,"POLYGON ((377772.229 3534595.104, 377753.854 3..."
4,APPLING-:-3C,246,934,3,1180,1427.934442,416.186300,57.464584,60.117966,1961.703292,"POLYGON ((386430.887 3520109.322, 386469.241 3..."

In [42]:
final_precincts.to_csv('Georgia/seawulf.csv', index=False)

In [43]:
final_precincts.to_file("Georgia/seawulf.gpkg", driver="GPKG")

### Congressional District

In [44]:
zip_path = "../data/Georgia/GA_congressional.zip"

congressional_df = gpd.read_file(
    f"zip://{zip_path}!Congress-2023 shape.shp"
)
print(congressional_df.shape)
congressional_df.head()

(14, 70)

,ID,AREA,DATA,DISTRICT,POPULATION,F18_POP,NH_WHT,NH_BLK,HISPANIC_O,NH_ASN,...,F_NH_2_RAC,IDEAL_VALU,F_18_AP_WH,F_18_AP_IN,F_18_AP_AS,F_18_AP_HW,F_18_AP_OT,F_18_2_RAC,DISTRICT_L,geometry
0,1,10127.426758,2,002,765137,587555,305611,375124,45499,10263,...,0.040245,765136.0,0.468327,0.015445,0.018934,0.002189,0.043899,0.038509,002|0%,"POLYGON ((-84.6946 32.58394, -84.6946 32.58407..."
1,2,4251.204102,3,003,765136,586319,492494,173004,48285,15959,...,0.050984,765136.0,0.723775,0.020902,0.025469,0.001184,0.048032,0.049671,003|0%,"POLYGON ((-84.99934 32.50726, -84.99944 32.507..."
2,3,8162.467285,1,001,765137,589266,440636,210695,59328,16737,...,0.053195,765136.0,0.666193,0.020010,0.029893,0.002915,0.054580,0.051632,001|0%,"POLYGON ((-82.43153 31.96618, -82.43095 31.966..."
3,4,11088.923828,8,008,765136,585857,443123,227430,54850,11916,...,0.040346,765136.0,0.655996,0.016308,0.020273,0.001436,0.048297,0.039981,008|0%,"POLYGON ((-84.0415 33.20263, -84.04115 33.2026..."
4,5,9829.969727,12,012,765136,588119,398843,276358,43065,14024,...,0.046987,765136.0,0.595143,0.016735,0.025544,0.002231,0.040080,0.043274,012|0%,"POLYGON ((-82.64545 33.9842, -82.64535 33.9841..."

In [45]:
congression_col = congressional_df.columns
print(congression_col)

Index(['ID', 'AREA', 'DATA', 'DISTRICT', 'POPULATION', 'F18_POP', 'NH_WHT',
       'NH_BLK', 'HISPANIC_O', 'NH_ASN', 'NH_IND', 'NH_HWN', 'NH_OTH',
       'NH_2_RACES', 'NH18_WHT', 'NH18_BLK', 'H18_POP', 'NH18_ASN', 'NH18_IND',
       'NH18_HWN', 'NH18_OTH', 'NH18_2_RAC', 'AP_WHT', 'AP_BLK', 'AP_IND',
       'AP_ASN', 'AP_HWN', 'AP_OTH', 'F18_AP_BLK', 'F18_AP_WHT', 'F18_AP_IND',
       'F18_AP_ASN', 'F18_AP_HWN', 'F18_AP_OTH', 'F18_2_RACE', 'DEVIATION',
       'F_DEVIATIO', 'F_18_POP', 'F_NH_WHT', 'F_NH_BLK', 'F_HISPANIC',
       'F_NH_ASN', 'F_NH_IND', 'F_NH_HWN', 'F_NH_OTH', 'F_NH18_WHT',
       'F_NH18_BLK', 'F_H18_POP', 'F_NH18_ASN', 'F_NH18_IND', 'F_NH18_HWN',
       'F_NH18_OTH', 'F_AP_WHT', 'F_AP_BLK', 'F_AP_IND', 'F_AP_ASN',
       'F_AP_HWN', 'F_AP_OTH', 'F_18_AP_BL', 'F_NH18_2_R', 'F_NH_2_RAC',
       'IDEAL_VALU', 'F_18_AP_WH', 'F_18_AP_IN', 'F_18_AP_AS', 'F_18_AP_HW',
       'F_18_AP_OT', 'F_18_2_RAC', 'DISTRICT_L', 'geometry'],
      dtype='str')

In [46]:
filtered_congression_col = [x for x in congression_col if '18' not in x and 'F_' not in x and 'AP' not in x]
filtered_congression_col
remove = ['DEVIATION', 'IDEAL_VALU', 'DISTRICT_L']
filtered_congression_col = [x for x in filtered_congression_col if x not in remove]
filtered_congression_col

['ID',
 'AREA',
 'DATA',
 'DISTRICT',
 'POPULATION',
 'NH_WHT',
 'NH_BLK',
 'HISPANIC_O',
 'NH_ASN',
 'NH_IND',
 'NH_HWN',
 'NH_OTH',
 'NH_2_RACES',
 'geometry']

In [47]:
filtered_congression_df = congressional_df[filtered_congression_col]
print(filtered_congression_df.shape)
filtered_congression_df.head()

(14, 14)

,ID,AREA,DATA,DISTRICT,POPULATION,NH_WHT,NH_BLK,HISPANIC_O,NH_ASN,NH_IND,NH_HWN,NH_OTH,NH_2_RACES,geometry
0,1,10127.426758,2,002,765137,305611,375124,45499,10263,1616,748,2630,23646,"POLYGON ((-84.6946 32.58394, -84.6946 32.58407..."
1,2,4251.204102,3,003,765136,492494,173004,48285,15959,1632,291,3578,29893,"POLYGON ((-84.99934 32.50726, -84.99944 32.507..."
2,3,8162.467285,1,001,765137,440636,210695,59328,16737,1824,1198,3373,31346,"POLYGON ((-82.43153 31.96618, -82.43095 31.966..."
3,4,11088.923828,8,008,765136,443123,227430,54850,11916,1435,357,2388,23637,"POLYGON ((-84.0415 33.20263, -84.04115 33.2026..."
4,5,9829.969727,12,012,765136,398843,276358,43065,14024,1627,822,2763,27634,"POLYGON ((-82.64545 33.9842, -82.64535 33.9841..."

In [48]:
dict_race = {'NH_WHT': 'White', 'NH_BLK': 'Black', 'HISPANIC_O': 'Latino', 'POPULATION': 'Total Population', 'DISTRICT': 'District'}
filtered_congression_df = filtered_congression_df.rename(columns=dict_race)
filtered_congression_df.head()

,ID,AREA,DATA,District,Total Population,White,Black,Latino,NH_ASN,NH_IND,NH_HWN,NH_OTH,NH_2_RACES,geometry
0,1,10127.426758,2,002,765137,305611,375124,45499,10263,1616,748,2630,23646,"POLYGON ((-84.6946 32.58394, -84.6946 32.58407..."
1,2,4251.204102,3,003,765136,492494,173004,48285,15959,1632,291,3578,29893,"POLYGON ((-84.99934 32.50726, -84.99944 32.507..."
2,3,8162.467285,1,001,765137,440636,210695,59328,16737,1824,1198,3373,31346,"POLYGON ((-82.43153 31.96618, -82.43095 31.966..."
3,4,11088.923828,8,008,765136,443123,227430,54850,11916,1435,357,2388,23637,"POLYGON ((-84.0415 33.20263, -84.04115 33.2026..."
4,5,9829.969727,12,012,765136,398843,276358,43065,14024,1627,822,2763,27634,"POLYGON ((-82.64545 33.9842, -82.64535 33.9841..."

In [49]:
others_col = ['NH_ASN', 'NH_IND', 'NH_HWN', 'NH_OTH','NH_2_RACES']
filtered_congression_df['Other'] = filtered_congression_df[others_col].sum(axis=1)
filtered_congression_df = filtered_congression_df.drop(columns=others_col)
filtered_congression_df

,ID,AREA,DATA,District,Total Population,White,Black,Latino,geometry,Other
0,1,10127.426758,2,002,765137,305611,375124,45499,"POLYGON ((-84.6946 32.58394, -84.6946 32.58407...",38903
1,2,4251.204102,3,003,765136,492494,173004,48285,"POLYGON ((-84.99934 32.50726, -84.99944 32.507...",51353
2,3,8162.467285,1,001,765137,440636,210695,59328,"POLYGON ((-82.43153 31.96618, -82.43095 31.966...",54478
3,4,11088.923828,8,008,765136,443123,227430,54850,"POLYGON ((-84.0415 33.20263, -84.04115 33.2026...",39733
4,5,9829.969727,12,012,765136,398843,276358,43065,"POLYGON ((-82.64545 33.9842, -82.64535 33.9841...",46870
5,6,2961.525635,14,014,765136,535516,90776,91371,"POLYGON ((-84.76749 33.7869, -84.77711 33.7856...",47473
6,7,523.350342,6,006,765136,227858,383970,94388,"POLYGON ((-84.76598 33.7166, -84.76548 33.7169...",58920
7,8,1503.135254,11,011,765135,510228,87548,92947,"POLYGON ((-84.65452 34.58319, -84.65452 34.583...",74412
8,9,226.288971,5,005,765137,237353,380936,75635,"POLYGON ((-84.41321 33.8054, -84.41251 33.8049...",71213
9,10,273.653931,4,004,765137,150803,363780,147267,"POLYGON ((-84.34809 33.88209, -84.34814 33.884...",103287
10,11,543.590088,13,013,765136,188099,379689,110825,"POLYGON ((-83.84318 33.89478, -83.84529 33.893...",86523
11,12,1159.227905,7,007,765137,487523,59278,78323,"POLYGON ((-84.34555 34.56274, -84.34556 34.562...",140013
12,13,3463.198486,9,009,765135,466010,91138,123476,"POLYGON ((-83.81768 34.12749, -83.81772 34.127...",84511
13,14,5343.096680,10,010,765137,478059,178393,58198,"POLYGON ((-83.10367 34.53662, -83.10368 34.536...",50487

In [50]:
print(filtered_congression_df.columns)

Index(['ID', 'AREA', 'DATA', 'District', 'Total Population', 'White', 'Black',
       'Latino', 'geometry', 'Other'],
      dtype='str')

In [51]:
filtered_congression_df["District"] = filtered_congression_df["District"].astype(int)
filtered_congression_df

,ID,AREA,DATA,District,Total Population,White,Black,Latino,geometry,Other
0,1,10127.426758,2,2,765137,305611,375124,45499,"POLYGON ((-84.6946 32.58394, -84.6946 32.58407...",38903
1,2,4251.204102,3,3,765136,492494,173004,48285,"POLYGON ((-84.99934 32.50726, -84.99944 32.507...",51353
2,3,8162.467285,1,1,765137,440636,210695,59328,"POLYGON ((-82.43153 31.96618, -82.43095 31.966...",54478
3,4,11088.923828,8,8,765136,443123,227430,54850,"POLYGON ((-84.0415 33.20263, -84.04115 33.2026...",39733
4,5,9829.969727,12,12,765136,398843,276358,43065,"POLYGON ((-82.64545 33.9842, -82.64535 33.9841...",46870
5,6,2961.525635,14,14,765136,535516,90776,91371,"POLYGON ((-84.76749 33.7869, -84.77711 33.7856...",47473
6,7,523.350342,6,6,765136,227858,383970,94388,"POLYGON ((-84.76598 33.7166, -84.76548 33.7169...",58920
7,8,1503.135254,11,11,765135,510228,87548,92947,"POLYGON ((-84.65452 34.58319, -84.65452 34.583...",74412
8,9,226.288971,5,5,765137,237353,380936,75635,"POLYGON ((-84.41321 33.8054, -84.41251 33.8049...",71213
9,10,273.653931,4,4,765137,150803,363780,147267,"POLYGON ((-84.34809 33.88209, -84.34814 33.884...",103287
10,11,543.590088,13,13,765136,188099,379689,110825,"POLYGON ((-83.84318 33.89478, -83.84529 33.893...",86523
11,12,1159.227905,7,7,765137,487523,59278,78323,"POLYGON ((-84.34555 34.56274, -84.34556 34.562...",140013
12,13,3463.198486,9,9,765135,466010,91138,123476,"POLYGON ((-83.81768 34.12749, -83.81772 34.127...",84511
13,14,5343.096680,10,10,765137,478059,178393,58198,"POLYGON ((-83.10367 34.53662, -83.10368 34.536...",50487

#### congressional demographic

In [52]:
congressional_demographic_col = ['District', 'Total Population', 'White', 'Black', 'Latino', 'Other']
congressional_demographic_df = (filtered_congression_df[congressional_demographic_col].sort_values(by='District'))
congressional_demographic_df.head()

   District  Total Population   White   Black  Latino   Other
2         1            765137  440636  210695   59328   54478
0         2            765137  305611  375124   45499   38903
1         3            765136  492494  173004   48285   51353
9         4            765137  150803  363780  147267  103287
8         5            765137  237353  380936   75635   71213

In [53]:
congressional_demographic_df.to_csv("georgia/congressional_demographic.csv", index=False)

In [54]:
total_others = congressional_demographic_df['Other'].sum()
total_white = congressional_demographic_df['White'].sum()
total_black = congressional_demographic_df['Black'].sum()
total_latino = congressional_demographic_df['Latino'].sum()
print(f"total other: {total_others}, white: {total_white}, black: {total_black}, latino: {total_latino}")

total other: 948176, white: 5362156, black: 3278119, latino: 1123457

#### congressional boundaries

In [55]:
congresional_boundaries_col = ['District', 'geometry']
congressional_boundaries_df = (
    filtered_congression_df[congresional_boundaries_col]
    .sort_values(by='District')
)

congressional_boundaries_df.head()

   District                                           geometry
2         1  POLYGON ((-82.43153 31.96618, -82.43095 31.966...
0         2  POLYGON ((-84.6946 32.58394, -84.6946 32.58407...
1         3  POLYGON ((-84.99934 32.50726, -84.99944 32.507...
9         4  POLYGON ((-84.34809 33.88209, -84.34814 33.884...
8         5  POLYGON ((-84.41321 33.8054, -84.41251 33.8049...

In [56]:
congressional_boundaries_df.to_csv("georgia/congressional_boundaries.csv", index=False)

### GerryChain

In [57]:
import libpysal
from gerrychain import Graph

gdf = gpd.read_file("Georgia/seawulf.gpkg")
graph = Graph.from_geodataframe(gdf)

In [59]:
import networkx as nx

G = graph
print(nx.is_connected(G))

True