## Arizona Box Whisker Plot Data

### Imports

In [1]:
import pandas as pd
import json

### District Data Path to DataFrame

In [2]:
path = '../Georgia/congressional_demographic.csv'

In [3]:
district_cvap = pd.read_csv(path)
district_cvap

    District  Total Population   White   Black  Latino   Other
0          1            765137  440636  210695   59328   54478
1          2            765137  305611  375124   45499   38903
2          3            765136  492494  173004   48285   51353
3          4            765137  150803  363780  147267  103287
4          5            765137  237353  380936   75635   71213
5          6            765136  227858  383970   94388   58920
6          7            765137  487523   59278   78323  140013
7          8            765136  443123  227430   54850   39733
8          9            765135  466010   91138  123476   84511
9         10            765137  478059  178393   58198   50487
10        11            765135  510228   87548   92947   74412
11        12            765136  398843  276358   43065   46870
12        13            765136  188099  379689  110825   86523
13        14            765136  535516   90776   91371   47473

In [4]:
district_cvap.drop(columns=['District'], inplace=True)
district_cvap

    Total Population   White   Black  Latino   Other
0             765137  440636  210695   59328   54478
1             765137  305611  375124   45499   38903
2             765136  492494  173004   48285   51353
3             765137  150803  363780  147267  103287
4             765137  237353  380936   75635   71213
5             765136  227858  383970   94388   58920
6             765137  487523   59278   78323  140013
7             765136  443123  227430   54850   39733
8             765135  466010   91138  123476   84511
9             765137  478059  178393   58198   50487
10            765135  510228   87548   92947   74412
11            765136  398843  276358   43065   46870
12            765136  188099  379689  110825   86523
13            765136  535516   90776   91371   47473

### Race CVAP Enacted Plan Points

In [5]:
dfs = [None] * 4
groups = ['White', 'Black', 'Latino', 'Other']

In [6]:
def calculate_enacted_points(dfs, groups):
    for i, group in enumerate(groups):
        df = district_cvap[['Total Population', f'{group}']]
        df = df.sort_values(by=f'{group}').reset_index().drop(columns='index').reset_index()
        df['share'] = df[f'{group}'] / df['Total Population']
        df = df[['share']]

        dfs[i] = df
 
calculate_enacted_points(dfs, groups)

for df in dfs:
    print(df)

       share
0   0.197093
1   0.245837
2   0.297801
3   0.310210
4   0.399420
5   0.521271
6   0.575892
7   0.579143
8   0.609056
9   0.624802
10  0.637171
11  0.643669
12  0.666847
13  0.699896
       share
0   0.077474
1   0.114422
2   0.118640
3   0.119114
4   0.226109
5   0.233152
6   0.275369
7   0.297241
8   0.361188
9   0.475444
10  0.490270
11  0.496237
12  0.497866
13  0.501832
       share
0   0.056284
1   0.059465
2   0.063106
3   0.071687
4   0.076062
5   0.077539
6   0.098852
7   0.102365
8   0.119418
9   0.121478
10  0.123361
11  0.144844
12  0.161378
13  0.192471
       share
0   0.050844
1   0.051929
2   0.061257
3   0.062045
4   0.065984
5   0.067116
6   0.071200
7   0.077006
8   0.093072
9   0.097253
10  0.110452
11  0.113082
12  0.134992
13  0.182991

In [7]:
white_share = dfs[0].to_dict()
black_share = dfs[1].to_dict()
latino_share = dfs[2].to_dict()
other_share = dfs[3].to_dict()

ga_enacted_shares = {'white': white_share, 'black': black_share, 'latino': latino_share, 'other': other_share}

In [8]:
with open('../output/Georgia/ga-enacted-shares.json','a') as file:
    file.write(json.dumps(ga_enacted_shares,indent=4))

### Validation

In [9]:
with open('../output/Georgia/ga-enacted-shares.json') as json_file:
    data = json.load(json_file)

data

{'white': {'share': {'0': 0.19709280821604497,
   '1': 0.2458373413353966,
   '2': 0.2978006524330315,
   '3': 0.3102098055642323,
   '4': 0.39941997315513433,
   '5': 0.5212707283411053,
   '6': 0.5758916377067114,
   '7': 0.5791427929152464,
   '8': 0.6090559182366511,
   '9': 0.6248018328743742,
   '10': 0.6371708595976929,
   '11': 0.6436685765667803,
   '12': 0.6668470269952361,
   '13': 0.6998964889901926}},
 'black': {'share': {'0': 0.07747370732300228,
   '1': 0.11442163801159272,
   '2': 0.11864034629137826,
   '3': 0.11911362047220425,
   '4': 0.226108822483846,
   '5': 0.23315171008590618,
   '6': 0.27536898620769873,
   '7': 0.29724127475376927,
   '8': 0.3611880763681228,
   '9': 0.47544426684371555,
   '10': 0.4902703698814722,
   '11': 0.4962372702369252,
   '12': 0.49786639516844694,
   '13': 0.5018323539867422}},
 'latino': {'share': {'0': 0.05628411158277744,
   '1': 0.05946516767585413,
   '2': 0.06310642813826561,
   '3': 0.07168660212040735,
   '4': 0.07606219539768695,
   '5': 0.07753905509732244,
   '6': 0.09885157821409761,
   '7': 0.1023646745615491,
   '8': 0.11941798582212836,
   '9': 0.1214779091271475,
   '10': 0.1233610756780494,
   '11': 0.1448435310846699,
   '12': 0.16137805746698294,
   '13': 0.19247141361612366}},
 'other': {'share': {'0': 0.05084448928753935,
   '1': 0.05192933021057694,
   '2': 0.061257083707994396,
   '3': 0.06204517889630079,
   '4': 0.06598426164203273,
   '5': 0.06711617281110809,
   '6': 0.07120032098826747,
   '7': 0.07700591790217687,
   '8': 0.09307222105322314,
   '9': 0.09725342586602365,
   '10': 0.11045240382416174,
   '11': 0.1130818573430083,
   '12': 0.1349915113241158,
   '13': 0.18299075851775565}}}