In [104]:
import numpy as np
import pandas as pd
import geopandas as gpd

In [105]:
ga_df = gpd.read_file("../output/Georgia/ga_seawulf.gpkg")
ar_df = gpd.read_file("../output/Arkansas/ar_seawulf.gpkg")

In [106]:
ga_df.columns

Index(['Unique_id', 'Countyfp', 'Kamala d. harris', 'Donald j. trump',
       'Other_candidates', 'Total_votes', 'White_population',
       'Black_population', 'Latino_population', 'Other_population',
       'Total_population', 'District', 'White_harris_pct', 'Black_harris_pct',
       'Latino_harris_pct', 'Other_harris_pct', 'White_trump_pct',
       'Black_trump_pct', 'Latino_trump_pct', 'Other_trump_pct', 'geometry'],
      dtype='object')

In [107]:
races = ['White', 'Black', 'Latino', 'Other']

for race in races:
    ar_df[f"{race}_harris_votes"] = ar_df[f"{race}_population"]*ar_df[f"{race}_harris_pct"]
    ar_df[f"{race}_trump_votes"] = ar_df[f"{race}_population"]*ar_df[f"{race}_trump_pct"]
    ga_df[f"{race}_harris_votes"] = ga_df[f"{race}_population"]*ga_df[f"{race}_harris_pct"]
    ga_df[f"{race}_trump_votes"] = ga_df[f"{race}_population"]*ga_df[f"{race}_trump_pct"]

In [ ]:
columns_drop = ['Kamala d. harris', 'Donald j. trump',
       'Other_candidates', 'Total_votes', 'White_population',
       'Black_population', 'Latino_population', 'Other_population',
       'Total_population', 'White_harris_pct', 'Black_harris_pct',
       'Latino_harris_pct', 'Other_harris_pct', 'White_trump_pct',
       'Black_trump_pct', 'Latino_trump_pct', 'Other_trump_pct',]

In [108]:
ar_prefer_df = ar_df.drop(columns=columns_drop)
ga_prefer_df = ga_df.drop(columns=columns_drop)

In [109]:
ar_grouped = ar_prefer_df.groupby("District").sum(numeric_only=True)

In [110]:
ar_grouped

,White_harris_votes,White_trump_votes,Black_harris_votes,Black_trump_votes,Latino_harris_votes,Latino_trump_votes,Other_harris_votes,Other_trump_votes
District,,,,,,,,
1,68171.340127,370054.689507,67690.542048,20986.772876,8537.201770,4369.702605,6597.792263,9167.711984
2,108965.712731,293769.919598,100273.187857,11401.112971,12423.943222,5762.291683,7566.963960,9877.188918
3,115074.826055,305908.238372,11722.843845,2198.647120,32999.524329,15984.369139,14113.769748,18795.866506
4,57594.573067,346645.398302,86206.438136,21077.573512,14111.992779,7949.532897,6614.905139,9366.043692

In [112]:
ar_preferred_candidates = {}
for district_id, district in ar_grouped.iterrows():
    
    ar_preferred_candidates[district_id] = {}
    for race in races:
        cand = "Trump"
        if district[f"{race}_harris_votes"] > district[f"{race}_trump_votes"]:
            cand = "Harris"
        ar_preferred_candidates[district_id][race] = cand

ar_preferred_candidates

{1: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Trump'},
 2: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Trump'},
 3: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Trump'},
 4: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Trump'}}

In [115]:
ga_grouped = ga_prefer_df.groupby("District").sum(numeric_only=True)

In [116]:
ga_grouped

,White_harris_votes,White_trump_votes,Black_harris_votes,Black_trump_votes,Latino_harris_votes,Latino_trump_votes,Other_harris_votes,Other_trump_votes
District,,,,,,,,
1,64690.022646,292672.054201,151722.552113,13309.335125,21548.965746,10051.461228,22701.381059,1986.880431
2,39185.100412,207111.690018,249523.458016,30953.856246,13957.422494,5438.514084,18470.342911,1582.481712
3,48500.333420,337133.958104,118970.737010,12774.887810,16866.691091,7076.004992,19174.032511,1701.440110
4,43215.863718,83871.371450,265123.685754,7836.948464,29554.819701,10047.695863,45384.937053,3782.342070
5,138127.882903,60639.598616,276803.433934,6019.344356,26042.960430,7818.641316,41354.616736,2696.751010
6,72638.750722,112940.116213,281805.896172,9504.426887,29689.837085,10125.783780,25491.136887,1999.071259
7,79717.604078,305015.313255,43091.559785,2634.870871,25931.306397,11020.760092,51173.192639,5641.562053
8,37103.029677,316227.900971,145060.241935,27721.081287,16960.926294,8230.328019,16662.136733,1541.236657
9,46310.569693,336363.234999,62334.170631,4037.947296,35042.164815,15858.260183,37794.880060,3421.039862
10,70405.052384,314540.744081,135762.185525,12531.128144,20823.810737,8647.780302,25953.550510,2370.662479
11,89001.497246,328448.142284,66709.061234,4080.946667,28311.001323,12232.824414,29223.601365,2517.772163
12,44094.913821,273949.538295,182375.515896,28873.224704,16001.191129,6676.474933,21680.752226,1994.857069
13,36197.730764,114564.634179,277266.460806,10724.058339,31737.023457,11495.137767,42779.557647,3456.339217
14,58711.345611,368968.960858,64722.922235,4879.487157,26781.134914,14181.459962,19419.313068,1738.262450

In [117]:
ga_preferred_candidates = {}
for district_id, district in ga_grouped.iterrows():
    
    ga_preferred_candidates[district_id] = {}
    for race in races:
        cand = "Trump"
        if district[f"{race}_harris_votes"] > district[f"{race}_trump_votes"]:
            cand = "Harris"
        ga_preferred_candidates[district_id][race] = cand

ga_preferred_candidates

{1: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 2: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 3: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 4: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 5: {'White': 'Harris',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 6: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 7: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 8: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 9: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 10: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 11: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 12: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 13: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'},
 14: {'White': 'Trump',
  'Black': 'Harris',
  'Latino': 'Harris',
  'Other': 'Harris'}}

In [140]:
ar_preferred_district = pd.DataFrame.from_dict(ar_preferred_candidates, orient='index')
ga_preferred_district = pd.DataFrame.from_dict(ga_preferred_candidates, orient='index')

In [141]:
ar_preferred_district = ar_preferred_district.reset_index()
ar_preferred_district = ar_preferred_district.rename(columns={'index': 'District'})
ar_preferred_district.head()

   District  White   Black  Latino  Other
0         1  Trump  Harris  Harris  Trump
1         2  Trump  Harris  Harris  Trump
2         3  Trump  Harris  Harris  Trump
3         4  Trump  Harris  Harris  Trump

In [142]:
ga_preferred_district = ga_preferred_district.reset_index()
ga_preferred_district = ga_preferred_district.rename(columns={'index': 'District'})
ga_preferred_district.head()

   District   White   Black  Latino   Other
0         1   Trump  Harris  Harris  Harris
1         2   Trump  Harris  Harris  Harris
2         3   Trump  Harris  Harris  Harris
3         4   Trump  Harris  Harris  Harris
4         5  Harris  Harris  Harris  Harris

In [ ]:
ga_preferred_district.to_csv('../output/Georgia/ga_preferred_candidates.csv', index=False)

In [189]:
ar_preferred_district.to_csv('../output/Arkansas/ar_preferred_candidates.csv', index=False)

In [122]:
ar_state = ar_grouped.sum()
ar_statewide_winner = {}

for race in races:
    h = ar_state[f"{race}_harris_votes"]
    t = ar_state[f"{race}_trump_votes"]
    
    ar_statewide_winner[race] = "Harris" if h > t else "Trump"
    
ar_statewide_winner

{'White': 'Trump', 'Black': 'Harris', 'Latino': 'Harris', 'Other': 'Trump'}

In [123]:
ga_state = ar_grouped.sum()
ga_statewide_winner = {}

for race in races:
    h = ga_state[f"{race}_harris_votes"]
    t = ga_state[f"{race}_trump_votes"]
    
    ga_statewide_winner[race] = "Harris" if h > t else "Trump"
    
ga_statewide_winner

{'White': 'Trump', 'Black': 'Harris', 'Latino': 'Harris', 'Other': 'Trump'}

In [124]:
h_total = sum(ga_state[f"{r}_harris_votes"] for r in races)
t_total = sum(ga_state[f"{r}_trump_votes"] for r in races)

ga_statewide_winner_all = "Harris" if h_total > t_total else "Trump"
print(f"overall winner for GA: {ga_statewide_winner_all}")

h_total = sum(ar_state[f"{r}_harris_votes"] for r in races)
t_total = sum(ar_state[f"{r}_trump_votes"] for r in races)

ar_statewide_winner_all = "Harris" if h_total > t_total else "Trump"
print(f"overall winner for AR: {ar_statewide_winner_all}")

overall winner for GA: Trump
overall winner for AR: Trump

## effective

In [179]:
ar_grouped = ar_df.groupby("District").sum(numeric_only=True)
ar_grouped.head()

,Kamala d. harris,Donald j. trump,Other_candidates,Total_votes,White_population,Black_population,Latino_population,Other_population,Total_population,White_harris_pct,...,Latino_trump_pct,Other_trump_pct,White_harris_votes,White_trump_votes,Black_harris_votes,Black_trump_votes,Latino_harris_votes,Latino_trump_votes,Other_harris_votes,Other_trump_votes
District,,,,,,,,,,,,,,,,,,,,,
1,72678,196288,5243,274209,446936.060518,91220.871131,13912.029066,18340.886211,570409.846926,106.295383,...,216.528554,343.937947,68171.340127,370054.689507,67690.542048,20986.772876,8537.201770,4369.702605,6597.792263,9167.711984
2,130594,180457,7686,318737,413183.062384,114196.395126,19557.093934,20337.956549,567274.507993,95.527361,...,126.782878,201.819051,108965.712731,293769.919598,100273.187857,11401.112971,12423.943222,5762.291683,7566.963960,9877.188918
3,111871,188484,8413,308768,433085.472862,14382.831392,52516.298707,38290.188876,538274.791837,174.655684,...,235.943909,375.841990,115074.826055,305908.238372,11722.843845,2198.647120,32999.524329,15984.369139,14113.769748,18795.866506
4,81551,193295,5160,280006,411523.709405,110273.925981,23725.074666,18594.189564,564116.899617,126.956493,...,266.206322,419.705065,57594.573067,346645.398302,86206.438136,21077.573512,14111.992779,7949.532897,6614.905139,9366.043692

In [180]:
ga_grouped = ga_df.groupby("District").sum(numeric_only=True)
ga_grouped

,Kamala d. harris,Donald j. trump,Other_candidates,Total_votes,White_population,Black_population,Latino_population,Other_population,Total_population,White_harris_pct,...,Latino_trump_pct,Other_trump_pct,White_harris_votes,White_trump_votes,Black_harris_votes,Black_trump_votes,Latino_harris_votes,Latino_trump_votes,Other_harris_votes,Other_trump_votes
District,,,,,,,,,,,,,,,,,,,,,
1,152270,210061,1981,364312,359508.291574,165949.798637,32638.521318,25364.253458,583460.864986,42.878556,...,62.724822,16.979328,64690.022646,292672.054201,151722.552113,13309.335125,21548.965746,10051.461228,22701.381059,1986.880431
2,172627,149355,1326,323308,247683.797600,281563.376186,20055.984497,20587.379206,569890.537489,37.846013,...,63.997741,18.090621,39185.100412,207111.690018,249523.458016,30953.856246,13957.422494,5438.514084,18470.342911,1582.481712
3,142790,266188,2410,411388,387780.529182,132632.283726,24769.712426,21449.842857,566632.368191,23.955376,...,52.531402,14.757530,48500.333420,337133.958104,118970.737010,12774.887810,16866.691091,7076.004992,19174.032511,1701.440110
4,235417,72440,3331,311188,129361.118906,274211.942433,40896.996481,50441.353014,494911.410834,46.677657,...,42.635703,11.713835,43215.863718,83871.371450,265123.685754,7836.948464,29554.819701,10047.695863,45384.937053,3782.342070
5,300487,48208,3585,352280,202737.151853,283876.336182,34943.523385,45031.196516,566588.207936,127.401587,...,63.971257,17.076790,138127.882903,60639.598616,276803.433934,6019.344356,26042.960430,7818.641316,41354.616736,2696.751010
6,279038,91949,3034,374021,188272.691332,292555.951492,41067.777110,28183.389211,550079.809145,70.245439,...,62.772548,17.603023,72638.750722,112940.116213,281805.896172,9504.426887,29689.837085,10125.783780,25491.136887,1999.071259
7,165683,260524,4806,431013,389379.297248,46012.434014,38263.070029,58592.298568,532247.099858,44.605412,...,48.576930,14.214146,79717.604078,305015.313255,43091.559785,2634.870871,25931.306397,11020.760092,51173.192639,5641.562053
8,119764,225593,1436,346793,354700.650575,173862.294818,26048.647623,18722.059815,573333.652831,23.591239,...,67.457013,18.376679,37103.029677,316227.900971,145060.241935,27721.081287,16960.926294,8230.328019,16662.136733,1541.236657
9,128460,265811,2964,397235,385098.271879,66759.117873,52619.237939,42391.297962,546867.925653,18.148546,...,41.028134,11.339938,46310.569693,336363.234999,62334.170631,4037.947296,35042.164815,15858.260183,37794.880060,3421.039862
10,164052,250670,2578,417300,387396.904148,149225.105801,30478.367819,29121.315612,596221.693381,29.811787,...,46.070882,13.124586,70405.052384,314540.744081,135762.185525,12531.128144,20823.810737,8647.780302,25953.550510,2370.662479
11,160500,258473,3956,422929,421639.325137,71194.398422,41968.203555,32612.444705,567414.371819,34.094742,...,42.910366,11.622399,89001.497246,328448.142284,66709.061234,4080.946667,28311.001323,12232.824414,29223.601365,2517.772163
12,148755,197823,1713,348291,319833.972446,212328.221089,23450.203914,24346.135571,579958.533019,38.879569,...,71.977070,20.314213,44094.913821,273949.538295,182375.515896,28873.224704,16001.191129,6676.474933,21680.752226,1994.857069
13,257187,102730,3311,363228,152690.621945,289174.705922,44666.736095,47440.312863,533972.376825,31.714441,...,37.185541,10.286858,36197.730764,114564.634179,277266.460806,10724.058339,31737.023457,11495.137767,42779.557647,3456.339217
14,120987,263292,2501,386780,430275.519296,70056.973533,42241.215202,21746.848769,564320.556800,19.230492,...,43.085504,11.204600,58711.345611,368968.960858,64722.922235,4879.487157,26781.134914,14181.459962,19419.313068,1738.262450

In [181]:
for district_id, district in ar_grouped.iterrows():
    harris = district['Kamala d. harris']
    trump = district['Donald j. trump']
    prefer = ar_preferred_district[ ar_preferred_district['District']== district_id]
    black_preferred = prefer['Black'].iloc[0]
    # print(f"black prefer: {black_preferred}")
    latino_preferred = prefer['Latino'].iloc[0]
    harris_won = False
    if(harris > trump):
        harris_won = True
        print(f"AR: harris won {district_id}")
    
    if black_preferred == "Harris" and harris_won:
        print(f"-- black prefer {black_preferred}, black prefer won")
    elif black_preferred == "Trump" and not harris_won:
        print(f"-- black prefer {black_preferred}, black prefer won")
    
    if latino_preferred == "Harris" and harris_won:
        print(f"-- latino prefer {latino_preferred}, latino prefer won")
    elif latino_preferred == "Trump" and not harris_won:
        print(f"-- latino prefer {latino_preferred}, latino prefer won")

print("*"*50)

ga_black_effective_cnt = 0
ga_latino_effective_cnt = 0
ga_district_scores = {}
for district_id, district in ga_grouped.iterrows():
    ga_district_scores[district_id] = 0
    harris = district['Kamala d. harris']
    trump = district['Donald j. trump']
    # print(f"harris: {harris}, trump: {trump}")
    
    prefer = ga_preferred_district[ ga_preferred_district['District']== district_id]
    black_preferred = prefer['Black'].iloc[0]
    latino_preferred = prefer['Latino'].iloc[0]
    
    harris_won = False
    if(harris  > trump):
        harris_won = True
        print(f"GA: harris won @ district {district_id}") 
    
    minority_won = False
    if black_preferred == "Harris" and harris_won:
        ga_black_effective_cnt +=1
        minority_won = True
        print(f"-- black prefer {black_preferred}, black prefer won")
    elif black_preferred == "Trump" and not harris_won:
        ga_black_effective_cnt +=1
        minority_won = True
        print(f"-- black prefer {black_preferred}, black prefer won")
    
    if latino_preferred == "Harris" and harris_won:
        ga_black_effective_cnt +=1
        minority_won = True
        print(f"-- latino prefer {latino_preferred}, latino prefer won")
    elif latino_preferred == "Trump" and not harris_won:
        ga_black_effective_cnt +=1
        minority_won = True
        print(f"-- latino prefer {latino_preferred}, latino prefer won")
    
    if minority_won:
        ga_district_scores[district_id] = 1

print(ga_district_scores)
print(f"effective black: {ga_black_effective_cnt}, effective latino: {ga_latino_effective_cnt}")

**************************************************
GA: harris won @ district 2
-- black prefer Harris, black prefer won
-- latino prefer Harris, latino prefer won
GA: harris won @ district 4
-- black prefer Harris, black prefer won
-- latino prefer Harris, latino prefer won
GA: harris won @ district 5
-- black prefer Harris, black prefer won
-- latino prefer Harris, latino prefer won
GA: harris won @ district 6
-- black prefer Harris, black prefer won
-- latino prefer Harris, latino prefer won
GA: harris won @ district 13
-- black prefer Harris, black prefer won
-- latino prefer Harris, latino prefer won
{1: 0, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 1, 14: 0}
effective black: 10, effective latino: 0

In [182]:
ga_df.columns

Index(['Unique_id', 'Countyfp', 'Kamala d. harris', 'Donald j. trump',
       'Other_candidates', 'Total_votes', 'White_population',
       'Black_population', 'Latino_population', 'Other_population',
       'Total_population', 'District', 'White_harris_pct', 'Black_harris_pct',
       'Latino_harris_pct', 'Other_harris_pct', 'White_trump_pct',
       'Black_trump_pct', 'Latino_trump_pct', 'Other_trump_pct', 'geometry',
       'White_harris_votes', 'White_trump_votes', 'Black_harris_votes',
       'Black_trump_votes', 'Latino_harris_votes', 'Latino_trump_votes',
       'Other_harris_votes', 'Other_trump_votes'],
      dtype='object')

group control factor $c = \min(2k, 1)$

In [183]:
ga_black_scores = {}
ga_latino_scores = {}
ga_total_scores = {}
for district_id, score in ga_district_scores.items():
    district_data = ga_df[ga_df['District'] == district_id]
    black_population = district_data['Black_population'].iloc[0]
    latino_population = district_data['Latino_population'].iloc[0]
    total_population = district_data['Total_population'].iloc[0]
    total_min = black_population+latino_population
    print(f"total_population: {total_population}, total_min: {total_min}")
    ga_black_scores[district_id] = min(score, black_population/total_population*2)
    ga_latino_scores[district_id] = min(score, latino_population/total_population*2)
    ga_total_scores[district_id] = min(score, total_min/total_population*2)

print(f"black score: {ga_black_scores}")
print(f"latino score: {ga_latino_scores}")
print(f"total (combine black and latino): {ga_total_scores}")

total_population: 1235.8211463537332, total_min: 157.9862397097495
total_population: 483.167074224068, total_min: 175.20650590436057
total_population: 4890.321185195, total_min: 1416.8985896298445
total_population: 2689.533040474905, total_min: 2256.5876507879993
total_population: 4174.74506891983, total_min: 3194.572797196416
total_population: 2599.4482278619166, total_min: 1833.4092180655616
total_population: 4005.439619002105, total_min: 636.6769216602943
total_population: 1075.9455719803118, total_min: 168.1044978478235
total_population: 1518.6334020482602, total_min: 92.71058338494437
total_population: 4231.005063227284, total_min: 922.8878542104189
total_population: 7170.27620584507, total_min: 912.1517244810211
total_population: 2161.2151301234217, total_min: 92.68849021409666
total_population: 2753.8274273379247, total_min: 2468.8028222703847
total_population: 2421.4796779884837, total_min: 28.760605704808675
black score: {1: 0, 2: np.float64(0.7252411959293233), 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 1, 14: 0}
latino score: {1: 0, 2: np.float64(7.141728075638506e-07), 3: 0, 4: np.float64(0.055770786539118405), 5: np.float64(0.21558199831905026), 6: np.float64(0.1884750300362649), 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: np.float64(0.22657590582277537), 14: 0}
total (combine black and latino): {1: 0, 2: np.float64(0.7252419101021309), 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 1, 14: 0}

- use threshold 0.6 due to only 1 election available

In [184]:
threshold = 0.6
ga_benchmark_cnt = 0
for district_id, score in ga_black_scores.items():
    if score > 0.6:
        ga_benchmark_cnt+=1

print(f"benchmark effective state: {ga_benchmark_cnt}")

benchmark effective state: 5

In [197]:
pop_col = ['Total_population']
ga_district_pop = ga_grouped[pop_col]

In [198]:
ga_district_pop = ga_district_pop.reset_index()
ga_district_pop = ga_district_pop.rename(columns={'index':"District"})
ga_district_pop.head()

   District  Total_population
0         1     583460.864986
1         2     569890.537489
2         3     566632.368191
3         4     494911.410834
4         5     566588.207936

In [199]:
ideal = ga_district_pop["Total_population"].mean()

ga_district_pop["deviation"] = ga_district_pop["Total_population"] - ideal
ga_district_pop["pct_deviation"] = ga_district_pop["deviation"] / ideal * 100

In [200]:
ga_district_pop

    District  Total_population     deviation  pct_deviation
0          1     583460.864986  24468.050074       4.377167
1          2     569890.537489  10897.722577       1.949528
2          3     566632.368191   7639.553279       1.366664
3          4     494911.410834 -64081.404078     -11.463726
4          5     566588.207936   7595.393024       1.358764
5          6     550079.809145  -8913.005767      -1.594476
6          7     532247.099858 -26745.715054      -4.784626
7          8     573333.652831  14340.837919       2.565478
8          9     546867.925653 -12124.889259      -2.169060
9         10     596221.693381  37228.878469       6.659992
10        11     567414.371819   8421.556907       1.506559
11        12     579958.533019  20965.718107       3.750624
12        13     533972.376825 -25020.438087      -4.475986
13        14     564320.556800   5327.741888       0.953097

In [201]:
ar_district_pop = ar_grouped[pop_col]
ar_district_pop = ar_district_pop.reset_index()
ar_district_pop = ar_district_pop.rename(columns={'index':"District"})
ar_district_pop.head()
ideal = ar_district_pop["Total_population"].mean()

ar_district_pop["deviation"] = ar_district_pop["Total_population"] - ideal
ar_district_pop["pct_deviation"] = ar_district_pop["deviation"] / ideal * 100

In [202]:
ar_district_pop

   District  Total_population     deviation  pct_deviation
0         1     570409.846926  10390.835333       1.855443
1         2     567274.507993   7255.496400       1.295580
2         3     538274.791837 -21744.219756      -3.882765
3         4     564116.899617   4097.888024       0.731741