source: https://github.com/MEDSL/2024-elections-official/blob/main/individual_states/de24.zip

In [1]:
import geopandas
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../data/Georgia/ga24.csv")

In [3]:
print(f"shape: {df.shape}")
df.head()

shape: (71773, 24)

,precinct,office,party_detailed,party_simplified,mode,votes,county_name,county_fips,jurisdiction_name,jurisdiction_fips,...,stage,state,special,writein,state_po,state_fips,state_cen,state_ic,date,magnitude
0,Jack Strickland Community Center,US PRESIDENT,REPUBLICAN,REPUBLICAN,TOTAL,3366,CANDLER,13043.0,CANDLER,13043.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
1,Jack Strickland Community Center,US PRESIDENT,DEMOCRAT,DEMOCRAT,TOTAL,1196,CANDLER,13043.0,CANDLER,13043.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
2,Jack Strickland Community Center,US PRESIDENT,LIBERTARIAN,LIBERTARIAN,TOTAL,3,CANDLER,13043.0,CANDLER,13043.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
3,Jack Strickland Community Center,US PRESIDENT,GREEN,OTHER,TOTAL,3,CANDLER,13043.0,CANDLER,13043.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
4,Jack Strickland Community Center,US HOUSE,REPUBLICAN,REPUBLICAN,TOTAL,3407,CANDLER,13043.0,CANDLER,13043.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1

In [7]:
cols = df.columns
print(f"all columns: {cols}")

all columns: Index(['precinct', 'office', 'party_detailed', 'party_simplified', 'mode',
       'votes', 'county_name', 'county_fips', 'jurisdiction_name',
       'jurisdiction_fips', 'candidate', 'district', 'dataverse', 'year',
       'stage', 'state', 'special', 'writein', 'state_po', 'state_fips',
       'state_cen', 'state_ic', 'date', 'magnitude'],
      dtype='object')

In [3]:
df_sorted = df.sort_values(by=['county_fips', 'precinct'])
df_sorted.head()

,precinct,office,party_detailed,party_simplified,mode,votes,county_name,county_fips,jurisdiction_name,jurisdiction_fips,...,stage,state,special,writein,state_po,state_fips,state_cen,state_ic,date,magnitude
42615,1B,US PRESIDENT,REPUBLICAN,REPUBLICAN,TOTAL,921,APPLING,13001.0,APPLING,13001.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
42624,1B,US PRESIDENT,DEMOCRAT,DEMOCRAT,TOTAL,108,APPLING,13001.0,APPLING,13001.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
42633,1B,US PRESIDENT,LIBERTARIAN,LIBERTARIAN,TOTAL,2,APPLING,13001.0,APPLING,13001.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
42642,1B,US PRESIDENT,GREEN,OTHER,TOTAL,0,APPLING,13001.0,APPLING,13001.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1
42651,1B,US HOUSE,REPUBLICAN,REPUBLICAN,TOTAL,895,APPLING,13001.0,APPLING,13001.0,...,GEN,GEORGIA,False,False,GA,13,58,44,2024-11-05,1

In [4]:
df_sorted['GEOID'] = df_sorted['county_fips'].astype(str) + "-" + df_sorted['precinct'].astype(str)

In [5]:
df_sorted.head()

,precinct,office,party_detailed,party_simplified,mode,votes,county_name,county_fips,jurisdiction_name,jurisdiction_fips,...,state,special,writein,state_po,state_fips,state_cen,state_ic,date,magnitude,GEOID
42615,1B,US PRESIDENT,REPUBLICAN,REPUBLICAN,TOTAL,921,APPLING,13001.0,APPLING,13001.0,...,GEORGIA,False,False,GA,13,58,44,2024-11-05,1,13001.0-1B
42624,1B,US PRESIDENT,DEMOCRAT,DEMOCRAT,TOTAL,108,APPLING,13001.0,APPLING,13001.0,...,GEORGIA,False,False,GA,13,58,44,2024-11-05,1,13001.0-1B
42633,1B,US PRESIDENT,LIBERTARIAN,LIBERTARIAN,TOTAL,2,APPLING,13001.0,APPLING,13001.0,...,GEORGIA,False,False,GA,13,58,44,2024-11-05,1,13001.0-1B
42642,1B,US PRESIDENT,GREEN,OTHER,TOTAL,0,APPLING,13001.0,APPLING,13001.0,...,GEORGIA,False,False,GA,13,58,44,2024-11-05,1,13001.0-1B
42651,1B,US HOUSE,REPUBLICAN,REPUBLICAN,TOTAL,895,APPLING,13001.0,APPLING,13001.0,...,GEORGIA,False,False,GA,13,58,44,2024-11-05,1,13001.0-1B

In [8]:
column_to_drop = []
for col in cols:
    unique = df_sorted[col].unique()
    if len(unique)==1:
        print(f"{col} has only 1 unique value: {unique}")
        column_to_drop.append(col)
column_to_drop.append('precinct')
column_to_drop.append('county_fips')
column_to_drop

mode has only 1 unique value: ['TOTAL']
year has only 1 unique value: [2024]
state has only 1 unique value: ['GEORGIA']
state_po has only 1 unique value: ['GA']
state_fips has only 1 unique value: [13]
state_cen has only 1 unique value: [58]
state_ic has only 1 unique value: [44]
date has only 1 unique value: ['2024-11-05']

['mode',
 'year',
 'state',
 'state_po',
 'state_fips',
 'state_cen',
 'state_ic',
 'date',
 'precinct',
 'county_fips']

In [9]:
df_sorted = df_sorted.drop(column_to_drop, axis =1)

In [10]:
cols = df_sorted.columns.tolist()
cols.remove('GEOID')
cols = ['GEOID'] + cols

df_sorted = df_sorted[cols]
df_sorted

,GEOID,office,party_detailed,party_simplified,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate,district,dataverse,stage,special,writein,magnitude
42615,13001.0-1B,US PRESIDENT,REPUBLICAN,REPUBLICAN,921,APPLING,APPLING,13001.0,DONALD J TRUMP,NaN,PRESIDENT,GEN,False,False,1
42624,13001.0-1B,US PRESIDENT,DEMOCRAT,DEMOCRAT,108,APPLING,APPLING,13001.0,KAMALA D HARRIS,NaN,PRESIDENT,GEN,False,False,1
42633,13001.0-1B,US PRESIDENT,LIBERTARIAN,LIBERTARIAN,2,APPLING,APPLING,13001.0,CHASE OLIVER,NaN,PRESIDENT,GEN,False,False,1
42642,13001.0-1B,US PRESIDENT,GREEN,OTHER,0,APPLING,APPLING,13001.0,JILL STEIN,NaN,PRESIDENT,GEN,False,False,1
42651,13001.0-1B,US HOUSE,REPUBLICAN,REPUBLICAN,895,APPLING,APPLING,13001.0,"EARL L ""BUDDY"" CARTER",001,HOUSE,GEN,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71768,nan-STATE FLOATING,US PRESIDENT,NaN,NaN,19,STATE FLOATING,STATE FLOATING,NaN,EMILY MATHEWS,NaN,PRESIDENT,GEN,False,True,1
71769,nan-STATE FLOATING,US PRESIDENT,NaN,NaN,9,STATE FLOATING,STATE FLOATING,NaN,ANDRE RAMON MCNEIL SR,NaN,PRESIDENT,GEN,False,True,1
71770,nan-STATE FLOATING,US HOUSE,NaN,NaN,45,STATE FLOATING,STATE FLOATING,NaN,ELFREDA DESVINGES,006,HOUSE,GEN,False,True,1
71771,nan-STATE FLOATING,US HOUSE,NaN,NaN,10226,STATE FLOATING,STATE FLOATING,NaN,TRAVEY VERHOEVEN,011,HOUSE,GEN,False,True,1
71772,nan-STATE FLOATING,STATE HOUSE,NaN,NaN,40,STATE FLOATING,STATE FLOATING,NaN,ROBERT MALLARD,139,STATE,GEN,False,True,1

In [11]:
candidates = df_sorted['candidate'].unique()
print(f"total number of candidates: {len(candidates)}")
print(f"candidates:\n {candidates}")

total number of candidates: 2324
candidates:
 ['DONALD J TRUMP' 'KAMALA D HARRIS' 'CHASE OLIVER' ... 'ELFREDA DESVINGES'
 'TRAVEY VERHOEVEN' 'ROBERT MALLARD']

In [14]:
first = df_sorted[df_sorted['GEOID'] == '13001.0-1B']
print(f"num of first precinct: {first.shape}")
print(f"columns:{first.columns}")

num of first precinct: (22, 15)
columns:Index(['GEOID', 'office', 'party_detailed', 'party_simplified', 'votes',
       'county_name', 'jurisdiction_name', 'jurisdiction_fips', 'candidate',
       'district', 'dataverse', 'stage', 'special', 'writein', 'magnitude'],
      dtype='object')

In [15]:
first

,GEOID,office,party_detailed,party_simplified,votes,county_name,jurisdiction_name,jurisdiction_fips,candidate,district,dataverse,stage,special,writein,magnitude
42615,13001.0-1B,US PRESIDENT,REPUBLICAN,REPUBLICAN,921,APPLING,APPLING,13001.0,DONALD J TRUMP,NaN,PRESIDENT,GEN,False,False,1
42624,13001.0-1B,US PRESIDENT,DEMOCRAT,DEMOCRAT,108,APPLING,APPLING,13001.0,KAMALA D HARRIS,NaN,PRESIDENT,GEN,False,False,1
42633,13001.0-1B,US PRESIDENT,LIBERTARIAN,LIBERTARIAN,2,APPLING,APPLING,13001.0,CHASE OLIVER,NaN,PRESIDENT,GEN,False,False,1
42642,13001.0-1B,US PRESIDENT,GREEN,OTHER,0,APPLING,APPLING,13001.0,JILL STEIN,NaN,PRESIDENT,GEN,False,False,1
42651,13001.0-1B,US HOUSE,REPUBLICAN,REPUBLICAN,895,APPLING,APPLING,13001.0,"EARL L ""BUDDY"" CARTER",001,HOUSE,GEN,False,False,1
42660,13001.0-1B,US HOUSE,DEMOCRAT,DEMOCRAT,97,APPLING,APPLING,13001.0,PATTI HEWITT,001,HOUSE,GEN,False,False,1
42669,13001.0-1B,STATE SENATE,REPUBLICAN,REPUBLICAN,907,APPLING,APPLING,13001.0,BLAKE TILLERY,019,STATE,GEN,False,False,1
42678,13001.0-1B,STATE HOUSE,REPUBLICAN,REPUBLICAN,875,APPLING,APPLING,13001.0,"WILLIAM ""BILL"" WERKHEISER",157,STATE,GEN,False,False,1
42690,13001.0-1B,APPLING COUNTY DISTRICT ATTORNEY,REPUBLICAN,REPUBLICAN,871,APPLING,APPLING,13001.0,KEITH HIGGINS,BRUNSWICK JUDICIAL CIRCUIT,LOCAL,GEN,False,False,1
42699,13001.0-1B,SUPERIOR COURT CLERK,REPUBLICAN,REPUBLICAN,926,APPLING,APPLING,13001.0,MARSHA THOMAS,NaN,LOCAL,GEN,False,False,1
42708,13001.0-1B,APPLING COUNTY SHERIFF,REPUBLICAN,REPUBLICAN,839,APPLING,APPLING,13001.0,MARK MELTON,NaN,LOCAL,GEN,False,False,1
42717,13001.0-1B,TAX COMMISSION,REPUBLICAN,REPUBLICAN,879,APPLING,APPLING,13001.0,LACEY LEGGETT,NaN,LOCAL,GEN,False,False,1
42726,13001.0-1B,APPLING COUNTY SURVEYOR,REPUBLICAN,REPUBLICAN,878,APPLING,APPLING,13001.0,JERRY TOMBERLIN,NaN,LOCAL,GEN,False,False,1
42735,13001.0-1B,APPLING COUNTY CORONER,REPUBLICAN,REPUBLICAN,887,APPLING,APPLING,13001.0,HENRY JONES,NaN,LOCAL,GEN,False,False,1
42749,13001.0-1B,PROPOSED CONSTITUTIONAL AMENDMENT 1,NaN,NaN,515,APPLING,APPLING,13001.0,YES,NaN,STATE,GEN,False,False,1
42758,13001.0-1B,PROPOSED CONSTITUTIONAL AMENDMENT 1,NaN,NaN,400,APPLING,APPLING,13001.0,NO,NaN,STATE,GEN,False,False,1
42767,13001.0-1B,PROPOSED CONSTITUTIONAL AMENDMENT 2,NaN,NaN,356,APPLING,APPLING,13001.0,YES,NaN,STATE,GEN,False,False,1
42776,13001.0-1B,PROPOSED CONSTITUTIONAL AMENDMENT 2,NaN,NaN,553,APPLING,APPLING,13001.0,NO,NaN,STATE,GEN,False,False,1
42785,13001.0-1B,STATEWIDE REFERENDUM QUESTION A,NaN,NaN,484,APPLING,APPLING,13001.0,YES,NaN,STATE,GEN,False,False,1
42794,13001.0-1B,STATEWIDE REFERENDUM QUESTION A,NaN,NaN,452,APPLING,APPLING,13001.0,NO,NaN,STATE,GEN,False,False,1
42806,13001.0-1B,APPLING AD VALOREM TAX,NaN,NaN,548,APPLING,APPLING,13001.0,YES,NaN,LOCAL,GEN,False,False,1
42815,13001.0-1B,APPLING AD VALOREM TAX,NaN,NaN,384,APPLING,APPLING,13001.0,NO,NaN,LOCAL,GEN,False,False,1

In [16]:
unique_geoid = df_sorted['GEOID'].unique()
len(unique_geoid)

2702

In [19]:
parties = first['party_detailed'].unique()
print(parties)

['DEMOCRAT' 'REPUBLICAN' 'INDEPENDENT PARTY OF DELAWARE' 'CONSERVATIVE'
 'LIBERTARIAN']

In [34]:
office = first['office'].unique()
office

array(['US SENATE', 'KENT COUNTY CLERK OF THE PEACE', 'US PRESIDENT',
       'STATE HOUSE', 'KENT COUNTY REGISTER OF WILLS', 'GOVERNOR',
       'US HOUSE', 'LIEUTENANT GOVERNOR', 'INSURANCE COMMISSIONER'],
      dtype=object)