In [9]:
import pandas as pd
import numpy as np
import geopandas

In [10]:
df_de = geopandas.read_file("../data/Delaware/Precinct/de_nyt.geojson")
df_de = df_de.sort_values(by="GEOID")

columns_needed = ['GEOID', 'geometry']
de_precincts = df_de[columns_needed]
de_precincts['precinct'] = "Precinct " + df_de["GEOID"]

/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [11]:
de_precincts

,GEOID,geometry,precinct
0,10001-11-05,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905...",Precinct 10001-11-05
1,10001-11-06,"POLYGON ((-75.75449 39.22743, -75.75449 39.227...",Precinct 10001-11-06
2,10001-11-07,"POLYGON ((-75.69349 39.19968, -75.6935 39.1996...",Precinct 10001-11-07
3,10001-11-08,"POLYGON ((-75.64732 39.15437, -75.64734 39.154...",Precinct 10001-11-08
4,10001-11-09,"POLYGON ((-75.74776 39.14335, -75.74776 39.143...",Precinct 10001-11-09
...,...,...,...
520,10005-41-10,"POLYGON ((-75.23551 38.48005, -75.23551 38.480...",Precinct 10005-41-10
521,10005-41-11,"POLYGON ((-75.19192 38.47895, -75.19193 38.478...",Precinct 10005-41-11
522,10005-41-12,"POLYGON ((-75.18948 38.48168, -75.18857 38.482...",Precinct 10005-41-12
523,10005-41-13,"POLYGON ((-75.19192 38.47895, -75.19191 38.478...",Precinct 10005-41-13
524,10005-41-14,"POLYGON ((-75.17737 38.53138, -75.17696 38.531...",Precinct 10005-41-14

In [12]:
print(de_precincts.shape)
de_rows = len(de_precincts)
print(de_rows)

(526, 3)
526

In [23]:
de_precincts.loc[:, "total_population"] = np.random.randint(1000, 5001, size=de_rows)
de_precincts.loc[:, "latino_percentage"] = np.random.uniform(0,80, size=de_rows)
de_precincts.loc[:, "black_percentage"] = (100-de_precincts['latino_percentage'])*np.random.uniform(0, 1, size=de_rows)
de_precincts.loc[:, "other_percentage"] = (100 - de_precincts['latino_percentage'] - de_precincts['black_percentage'])

In [24]:
de_precincts

,GEOID,geometry,precinct,total_population,latino_percentage,black_percentage,other_percentage
0,10001-11-05,"POLYGON ((-75.6658 39.29057, -75.66581 39.2905...",Precinct 10001-11-05,3920,60.470147,19.080333,20.449519
1,10001-11-06,"POLYGON ((-75.75449 39.22743, -75.75449 39.227...",Precinct 10001-11-06,2856,35.956233,23.295082,40.748685
2,10001-11-07,"POLYGON ((-75.69349 39.19968, -75.6935 39.1996...",Precinct 10001-11-07,4359,47.801153,0.780062,51.418786
3,10001-11-08,"POLYGON ((-75.64732 39.15437, -75.64734 39.154...",Precinct 10001-11-08,1061,17.044324,74.793244,8.162431
4,10001-11-09,"POLYGON ((-75.74776 39.14335, -75.74776 39.143...",Precinct 10001-11-09,1289,65.302488,22.662228,12.035284
...,...,...,...,...,...,...,...
520,10005-41-10,"POLYGON ((-75.23551 38.48005, -75.23551 38.480...",Precinct 10005-41-10,1987,41.638141,23.070383,35.291476
521,10005-41-11,"POLYGON ((-75.19192 38.47895, -75.19193 38.478...",Precinct 10005-41-11,1786,72.378992,22.405286,5.215722
522,10005-41-12,"POLYGON ((-75.18948 38.48168, -75.18857 38.482...",Precinct 10005-41-12,4470,26.487457,59.249094,14.263449
523,10005-41-13,"POLYGON ((-75.19192 38.47895, -75.19191 38.478...",Precinct 10005-41-13,2821,27.227903,38.349529,34.422567
524,10005-41-14,"POLYGON ((-75.17737 38.53138, -75.17696 38.531...",Precinct 10005-41-14,3124,51.827759,14.274252,33.897988

In [26]:
df_ga = geopandas.read_file("../data/Georgia/Precinct/ga_nyt.geojson")
ga_precincts = df_ga[columns_needed]
ga_precincts['precinct'] = "Precinct " + df_ga["GEOID"]

/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [29]:
print(ga_precincts.shape)
ga_rows = len(ga_precincts)
print(ga_rows)

(2680, 3)
2680

In [30]:
ga_precincts.loc[:, "total_population"] = np.random.randint(1000, 5001, size=ga_rows)
ga_precincts.loc[:, "latino_percentage"] = np.random.uniform(0,80, size=ga_rows)
ga_precincts.loc[:, "black_percentage"] = (100-ga_precincts['latino_percentage'])*np.random.uniform(0, 1, size=ga_rows)
ga_precincts.loc[:, "other_percentage"] = (100 - ga_precincts['latino_percentage'] - ga_precincts['black_percentage'])

/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/xinyuesu/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [31]:
ga_precincts

,GEOID,geometry,precinct,total_population,latino_percentage,black_percentage,other_percentage
0,13001-4B,"POLYGON ((-82.31151 31.59099, -82.31149 31.590...",Precinct 13001-4B,2307,56.204642,35.515699,8.279659
1,13001-5B,"POLYGON ((-82.40153 31.69729, -82.40206 31.697...",Precinct 13001-5B,3180,57.327380,20.824108,21.848511
2,13001-3C,"POLYGON ((-82.13346 31.6308, -82.13346 31.6308...",Precinct 13001-3C,2641,59.541071,12.400230,28.058700
3,13001-2,"POLYGON ((-82.28049 31.84937, -82.2805 31.8493...",Precinct 13001-2,1296,48.536932,7.470867,43.992201
4,13001-1B,"POLYGON ((-82.29335 31.94084, -82.29344 31.940...",Precinct 13001-1B,1815,12.246339,60.523812,27.229849
...,...,...,...,...,...,...,...
2675,13321-01,"POLYGON ((-83.99673 31.5398, -83.99672 31.5398...",Precinct 13321-01,4816,75.362198,9.948316,14.689486
2676,13321-09,"POLYGON ((-83.79721 31.72736, -83.7972 31.7276...",Precinct 13321-09,3814,13.472231,68.750812,17.776958
2677,13321-03,"POLYGON ((-83.73692 31.62228, -83.73693 31.622...",Precinct 13321-03,2156,49.304957,26.855124,23.839919
2678,13321-15,"POLYGON ((-83.89245 31.64641, -83.89212 31.646...",Precinct 13321-15,3522,72.389389,9.847831,17.762779
2679,13321-14,"POLYGON ((-83.99673 31.5398, -83.99673 31.5397...",Precinct 13321-14,3094,16.642308,6.796982,76.560710

In [ ]:
print(ga_precincts['precinct'].isnull().sum())
print(de_precincts['precinct'].isnull().sum())

0
0

In [33]:
de_precincts.to_file("Delaware_precincts.geojson", driver="GeoJSON")
ga_precincts.to_file("Georgia_precincts.geojson", driver="GeoJSON")

In [34]:
!pip install geopandas topojson

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopandas in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (1.0.1)
Requirement already satisfied: topojson in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (1.10)
Requirement already satisfied: numpy>=1.22 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (0.11.1)
Requirement already satisfied: packaging in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=1.4.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.3.3)
Requirement already satisfied: pyproj>=3.3.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (3.6.1)
Requirement already satisfied: shapely>=2.0.0 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from geopandas) (2.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2025.3)
Requirement already satisfied: certifi in /Users/xinyuesu/Library/Python/3.9/lib/python/site-packages (from pyogrio>=0.7.2->geopandas) (2025.4.26)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.15.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [35]:
from topojson import Topology

In [36]:
gdf_ga = geopandas.read_file("Georgia_precincts.geojson")
gdf_de = geopandas.read_file("Delaware_precincts.geojson")

In [37]:
topology_ga = Topology(gdf_ga)
topology_de = Topology(gdf_de)
# Export TopoJSON
topology_ga.to_json("Georgia_precincts_topo.topojson")
topology_de.to_json("Delaware_precincts_topo.topojson")